yegor256/cactoos

- src/main/java/org/cactoos/io/InputAsText.java
- src/main/java/org/cactoos/io/TextAsInput.java
- src/test/java/org/cactoos/io/FileAsInputTest.java
- src/test/java/org/cactoos/io/InputAsBytesTest.java
- src/test/java/org/cactoos/io/InputAsTextTest.java
Now we are able to use charset to convert bytes to text and vice verse.
Default (`Charset.defaultCharset()`) charset is used in secondary constructors.
Part of #13
> Text encoding

- README.md
- src/main/java/org/cactoos/Proc.java
- src/main/java/org/cactoos/func/ConstFunc.java
- src/main/java/org/cactoos/func/DeadProc.java
- src/main/java/org/cactoos/func/ProcAsFunc.java
- src/main/java/org/cactoos/func/package-info.java
- src/main/java/org/cactoos/list/AllOf.java
- src/main/java/org/cactoos/list/AnyOf.java
- src/main/java/org/cactoos/list/IterableAsBoolean.java
- src/main/java/org/cactoos/list/IterableAsBooleans.java
- src/test/java/org/cactoos/list/AllOfTest.java
- src/test/java/org/cactoos/list/AnyOfTest.java
As per #18 
* `AllOf` and `AnyOf` introduced
* `Proc` interface added
* `ProcAsFunc` created
> #18: AnyOf, AllOf

- src/main/java/org/cactoos/Input.java
- src/main/java/org/cactoos/Output.java
- src/main/java/org/cactoos/io/BytesAsInput.java
- src/main/java/org/cactoos/io/DeadInput.java
- src/main/java/org/cactoos/io/DeadOutput.java
- src/main/java/org/cactoos/io/FileAsInput.java
- src/main/java/org/cactoos/io/FileAsOutput.java
- src/main/java/org/cactoos/io/InputAsBytes.java
- src/main/java/org/cactoos/io/InputStreamAsInput.java
- src/main/java/org/cactoos/io/LengthOfInput.java
- src/main/java/org/cactoos/io/OutputStreamAsOutput.java
- src/main/java/org/cactoos/io/ResourceAsInput.java
- src/main/java/org/cactoos/io/TeeInput.java
- src/main/java/org/cactoos/io/UrlAsInput.java
I renamed `Output` too, due the same reason of renamed `Input` interface.
> #54: Rename open() method in Input/Output interfaces

- src/main/java/org/cactoos/list/FilteredIterator.java
FilteredIterator can not support remove() operation at the current time in a correct way since it needs to look ahead on the underlying iterator.
Also read this Issue #82
> Removed remove() operation from FilteredIterator

- src/main/java/org/cactoos/func/FuncWithCallback.java
- src/main/java/org/cactoos/io/ResourceAsInput.java
- src/test/java/org/cactoos/func/FuncWithCallbackTest.java
as per #86: third argument for `FuncWithCallback` ctor introduced
> 86: third arg for FuncWithCallback

- src/main/java/org/cactoos/func/CachedScalar.java
- src/main/java/org/cactoos/func/UncheckedScalar.java
- src/main/java/org/cactoos/io/UncheckedBytes.java
- src/main/java/org/cactoos/list/IterableAsList.java
- src/main/java/org/cactoos/text/UncheckedText.java
- src/test/java/org/cactoos/func/UncheckedScalarTest.java
- src/test/java/org/cactoos/io/UncheckedBytesTest.java
- src/test/java/org/cactoos/text/UncheckedTextTest.java
This PR is based on PR #81 (would need to be merged prior to this PR) due to the usage of UncheckedScalar to be able to use CachedScalar class in a safe way (without requiring to declare size() an unsafe operation).
Closes #53 
Reasoning about the placement of the cache into IterableAsList and not into LengthOfIterable/LengthOfIterator
- LengthOfIterator: is a one-time use Object, it consumes the Iterator, therefore caching would alter how this works
- LengthOfIterable: Seemed a good spot, but the underlying iterable could change, therefore making the cached value inconsistent
- IterableAsList: Same argument here, the underlying iterable could change, but if it would change while being used here, the usage of this Class would not make much sense. Therefore the correct place to use the …
> #53 IterableAsList needs cached size()

- README.md
- src/main/java/org/cactoos/list/EndlessIterable.java
- src/main/java/org/cactoos/list/EndlessIterator.java
- src/main/java/org/cactoos/list/RepeatIterable.java
- src/main/java/org/cactoos/list/RepeatIterator.java
- src/test/java/org/cactoos/list/RepeatIterableTest.java
- src/test/java/org/cactoos/list/RepeatIteratorTest.java
as per #98:
* `EndlessIterator` introduced
* `EndlessIterable` introduced
* `Repeat` renamed to `RepeatIterable`
* `RepeatIterator` is now public
> 98: EndlessIterator

- src/main/java/org/cactoos/text/StringAsUrl.java
- src/main/java/org/cactoos/text/UrlAsString.java
- src/test/java/org/cactoos/text/StringAsUrlTest.java
- src/test/java/org/cactoos/text/UrlAsStringTest.java
As per #90:
- `StringAsUrl` introduced
- `UrlAsString` introduced
> #90: StringAsUrl and UrlAsString

- README.md
- src/main/java/org/cactoos/list/IterableAsList.java
No more calls to size() if not needed.
Modifications in the underlying Iterable would lead to inconsistent cache. Removed cache completely.
Caches do not work for modifyable Iterables.
> Removed calls to size() and cache from IterableAsList

- src/test/java/org/cactoos/func/StickyFuncTest.java
- src/test/java/org/cactoos/func/StickyScalarTest.java
as per #119: `StickyScalar` is now using `StickyFunc`
> #119: StickyScalar fixed

- src/test/java/org/cactoos/list/IterableAsMapTest.java
As per #152:
- Changed IterableAsMap to use types to avoid an apparently Eclipse IDE bug.
> #152: Eclipse cannot infer type arguments for IterableAsMap error

- src/main/java/org/cactoos/io/InputAsProperties.java
- src/test/java/org/cactoos/io/InputAsPropertiesTest.java
per #179: `InputAsProperties` introduced
> #179: InputAsProperties

- src/main/java/org/cactoos/io/InputAsLSInput.java
- src/main/java/org/cactoos/io/InputAsProperties.java
- src/main/java/org/cactoos/io/LengthOfInput.java
- src/main/java/org/cactoos/io/UncheckedInput.java
- src/main/java/org/cactoos/io/UncheckedOutput.java
- src/main/java/org/cactoos/text/StringAsUrl.java
- src/main/java/org/cactoos/text/UrlAsString.java
- src/test/java/org/cactoos/func/RetryFunc.java
- src/test/java/org/cactoos/io/InputAsPropertiesTest.java
> #208: more ctors and classes

- src/main/java/org/cactoos/list/ReverseIterable.java
- src/test/java/org/cactoos/list/ReverseIterableTest.java
> #242: ReverseIterable

- src/main/java/org/cactoos/text/JoinedText.java
- src/test/java/org/cactoos/text/JoinedTextTest.java
> #248: JoinedText ctors more useful

- src/test/java/org/cactoos/list/ReverseIterableTest.java
> #251: Let's do ReverseIterableTest use JoinedText

- src/test/java/org/cactoos/func/ChainedFuncTest.java
> #267: Eclipse cannot infer type arguments for ChainedFuncTest

- README.md
> #310: Objects vs. their static methods table updated

- src/main/java/org/cactoos/io/LengthOfInput.java
- src/test/java/org/cactoos/io/FileAsInputTest.java
- src/test/java/org/cactoos/io/InputAsLSInputTest.java
- src/test/java/org/cactoos/io/LengthOfInputTest.java
- src/test/java/org/cactoos/io/SlowInput.java
- src/test/java/org/cactoos/io/StickyInputTest.java
see #321 
The bug in `LengthOfInput` was reproduced and fixed.
> #321 fixed the issue

- src/test/java/org/cactoos/func/AndTest.java
> #327: Eclipse cannot infer type arguments for AndTest

- src/main/java/org/cactoos/func/AsyncFunc.java
may avoid the premature termination of the executor service...
> AsyncFunc: executor service as a field

- src/main/java/org/cactoos/io/BytesOf.java
- src/main/java/org/cactoos/io/InputStreamOf.java
- src/main/java/org/cactoos/io/OutputStreamTo.java
- src/main/java/org/cactoos/io/ReaderOf.java
- src/main/java/org/cactoos/io/WriterAsOutput.java
- src/main/java/org/cactoos/io/WriterAsOutputStream.java
- src/main/java/org/cactoos/io/WriterTo.java
- src/main/java/org/cactoos/text/TextOf.java
- src/test/java/org/cactoos/io/InputStreamOfTest.java
- src/test/java/org/cactoos/io/OutputStreamToTest.java
- src/test/java/org/cactoos/io/ReaderOfTest.java
- src/test/java/org/cactoos/io/StickyInputTest.java
- src/test/java/org/cactoos/io/WriterAsOutputStreamTest.java
- src/test/java/org/cactoos/io/WriterAsOutputTest.java
- src/test/java/org/cactoos/io/WriterToTest.java
- src/test/resources/org/cactoos/large-text.txt
see #378. Introduced these classes:
* `OutputStreamTo`
* `WriterAsOutput`
* `WriterAsOutput`
* `WriterAsOutputStream`
* `WriterTo`
* `ReaderOf`
> #378: ReaderOf, InputStreamOf, OutputStreamOf, etc.

- README.md
The README file has two lines for `StickyList` comparisons. This PR merges the two lines into one.
> README.md - Merging 'StickyList' comparisons

- src/main/java/org/cactoos/func/IoCheckedBiFunc.java
- src/main/java/org/cactoos/func/IoCheckedBiProc.java
- src/main/java/org/cactoos/func/IoCheckedFunc.java
- src/main/java/org/cactoos/func/IoCheckedProc.java
- src/main/java/org/cactoos/func/UncheckedBiFunc.java
- src/main/java/org/cactoos/func/UncheckedBiProc.java
- src/main/java/org/cactoos/func/UncheckedFunc.java
- src/main/java/org/cactoos/scalar/IoCheckedScalar.java
- src/main/java/org/cactoos/scalar/UncheckedScalar.java
- src/test/java/org/cactoos/func/IoCheckedBiFuncTest.java
- src/test/java/org/cactoos/func/IoCheckedFuncTest.java
- src/test/java/org/cactoos/func/IoCheckedProcTest.java
- src/test/java/org/cactoos/func/UncheckedFuncTest.java
- src/test/java/org/cactoos/func/UncheckedProcTest.java
- src/test/java/org/cactoos/scalar/IoCheckedScalarTest.java
Currently, the following chain of objects triggered when a single `UncheckedScalar`'s value evaluated:
`UncheckedScalar` -> `UncheckedFunc` -> `UncheckedBiFunc` -> `IoCheckedBiFunc` excluding Intermediate lambdas. I found this calls too expensive and fixed dependencies hell. In my version `UncheckedScalar` and `IoCncheckedScalar` do all the work themselves and other unchecked classes call them directly.
Additional tests which were missing for some reason added.
> Refactoring dependencies of Unhecked/IOChecked classes.

- src/main/java/org/cactoos/iterable/SyncIterable.java
- src/test/java/org/cactoos/iterable/SolidIterableTest.java
Replaced SyncIterable extending IterableEnvelope with implementing Iterable<> interface and synchronized access to iterator method
> #545 fixing SyncIterable thread-safety bug

- README.md
- src/main/java/org/cactoos/scalar/AvgOf.java
- src/test/java/org/cactoos/scalar/AvgOfTest.java
Fixing Issue #532 
After reading @vmotsak comments and also considering @svendiedrichsen input and reading a few more things on the theme, like [here](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html), [here](https://en.wikipedia.org/wiki/IEEE_754-1985) and [here](https://en.wikipedia.org/wiki/Average), I decided to go on the simplest solution for now, implementing what @vmotsak suggested.
Maybe in the future we can consider adding more number types of avg. calculation (as @svendiedrichsen suggested).
> #532 AvgOf() bug on Double edge values fixed

- README.md
- src/main/java/org/cactoos/scalar/AvgOf.java
- src/test/java/org/cactoos/scalar/AvgOfTest.java
#532 is mine now: https://github.com/yegor256/cactoos/issues/532#issuecomment-360486873 Based on #543 
Close #532 close #543
> #532 Declarative fix of AvgOf() bug on Double edge values

- src/test/java/org/cactoos/io/InputWithFallbackTest.java
> #537 Refactored InputWithFallbackTest to always fallback to the specified fallback Input

- src/main/java/org/cactoos/scalar/PropertiesOf.java
- src/test/java/org/cactoos/scalar/PropertiesOfTest.java
`PropertiesOf` implements interface `Scalar`and thus should be placed in the package of all scalar implementations.
> #590 moved PropertiesOf and its test to package scalar

- src/main/java/org/cactoos/list/Mapped.java
`org.cactoos.list.Mapped(Collection)` constructor is absolutely redundant because there is already a constructor accepting an `Iterable` which is less resource-consumable. Replacement of `ListOf` to `IterableOf` allows to spend fewer resources too.
> removed list.Mapped's constructor that accepts a Collection

- src/main/java/org/cactoos/matchers/TextHasString.java
- src/test/java/org/cactoos/io/Md5DigestOfTest.java
- src/test/java/org/cactoos/io/Sha1DigestOfTest.java
- src/test/java/org/cactoos/io/Sha256DigestOfTest.java
- src/test/java/org/cactoos/matchers/TextHasStringTest.java
- src/test/java/org/cactoos/matchers/package-info.java
- src/test/resources/org/cactoos/digest-calculation.txt
#580 Fix failed tests of digest invelope. Added clear description for TextHasString.
These tests were failed because Linux and Windows use different line spliterators, that is why they had different checksums in windows and linux that was the reason of failure. Moreover, the tests used DigestInvelope.class as a source of checking sum, which was the problem, because whenever you change that file, you should update new checksum in the tests, but as I said before different platforms have different checksum. More information [here](https://stackoverflow.com/questions/12289480/md5sum-different-on-linux-and-windows)
> #580 Fix failed tests of digest invelope.

- src/main/java/org/cactoos/io/SyncInput.java
- src/main/java/org/cactoos/io/SyncOutput.java
- src/main/java/org/cactoos/iterator/SyncIterator.java
- src/main/java/org/cactoos/scalar/SyncScalar.java
- src/main/java/org/cactoos/text/SyncText.java
This is fix of wrong javadocs in Sync... classes (see Issue #622).
> #622 Fix javadoc for all Sync... classes

- src/main/java/org/cactoos/scalar/Constant.java
- src/test/java/org/cactoos/scalar/ConstantTest.java
> Add Constant Scalar

- src/main/java/org/cactoos/scalar/ItemAt.java
- src/test/java/org/cactoos/scalar/ItemAtTest.java
As per #643 
I have refactored the class, so that it saves the value at the position specified in the constructor in a private property. When the `value()` method is called again, it simply returns the saved value.
Since we need to save the value inside the object, our class cannot be fully immutable (internally, it is still immutable from outside) as we need to return the value of type T on each method call. I think that using a list with a capacity of 1 element will suffice, although I do agree that this is a compromise.
> #643 - ItemAt object now returns correct value when used again

- src/test/java/org/cactoos/iterator/SyncIteratorTest.java
As per #585
I have written three multi-threaded tests for the `SyncIterator` class.
The first test deals with two concurrent `iterator.next()` method calls and tests that the calls are able to produce the correct output even when they are accessed concurrently.
The second test deals with two concurrent methods calls (`iterator.next()` and `iterator.hasNext()`).
The last added test has two concurrent `iterator.hasNext()` calls.
I have also added the `Concurrent` inner class that tests the supplied `Runnable`s for concurrency problems. I have constructed this class based on the information found [here](https://www.planetgeek.ch/2009/08/25/how-to-find-a-concurrency-bug-with-java/).
> #585 - Multi-threaded tests for SyncIterator class

- README.md
- src/test/java/org/cactoos/func/CallableOfTest.java
As per #666:
Added missing tests for these ctors:
* `CallableOf(final Runnable runnable)`
* `CallableOf(final Proc<X> proc)`
* `CallableOf(final Func<X, T> fnc, final X ipt)`
> (#666) Added unit tests for CallableOf

- src/test/java/org/cactoos/map/SolidMapTest.java
Issue #640. 
This pull request covers following SolidMap constructors with tests:
- `public SolidMap(final Map<X, Y> map, final Map.Entry<X, Y>... list)`
- `public <Z> SolidMap(final Func<Z, X> key, final Func<Z, Y> value, final Map<X, Y> map, final Iterable<Z> list)`
- `public <Z> SolidMap(final Func<Z, X> key, final Func<Z, Y> value, final Iterable<Z> list)`
> #640 Tests for SolidMap ctors

- src/test/java/org/cactoos/io/ReaderOfTest.java
Pull request for the issue #630. It increases test coverage of ReaderOf class up to 100%. All ctors are covered by successful tests now. No other changes.
> #630 ReaderOf test class is incomplete

- src/main/java/org/cactoos/scalar/And.java
- src/main/java/org/cactoos/scalar/AndInThreads.java
- src/test/java/org/cactoos/scalar/AndInThreadsTest.java
In the issue #677 explained why iterator as a parameter is a bad idea, so I just removed ctors with `Iterator` for `And`, `AndInThreads`
> #677 removed ctors with iterator for And's classes

- src/test/java/org/cactoos/func/SyncFuncTest.java
This pull request fixes issue #673: it adds unit tests for the following ctors of SyncFunc class: 
```
SyncFunc(final Runnable runnable)
SyncFunc(final Callable<Y> callable)
SyncFunc(final Proc<X> proc)
```
So after merging of this pull request class SyncFunc will have 100% test coverage.
> #673: Cover all ctors of SyncFunc with unit tests

- src/main/java/org/cactoos/map/MapOf.java
For #659 
**Problem**
Following code is failing:
```Java
@Test
public void createsMapFromIterator() {
MatcherAssert.assertThat(
"Can't create a map from Iterator with Entries.",
new MapOf<Integer, Integer>(
new ListOf<Map.Entry<Integer, Integer>>(
new MapEntry<Integer, Integer>(0, 0),
new MapEntry<Integer, Integer>(1, 1)
).iterator()
),
Matchers.allOf(
Matchers.hasEntry(0, 0),
Matchers.hasEntry(1, 1)
)
);
}
```
**Reason**
In Java we can use iterator only once.
**Solution**
Remove ctor with iterator according to #677
> #659 remove ctor

- src/test/java/org/cactoos/func/AsyncFuncTest.java
For #665 
**Problem**
There aren't tests for following ctors:
```Java
public AsyncFunc(final Proc<X> proc, final ThreadFactory fct)
public AsyncFunc(final Proc<X> proc, final ExecutorService exec)
```
**Solution**
Added two test for both untested ctors. Where tested thread name to ensure `Proc` executed with specific `ThreadFactory`/`ExecutorService` and a side effect in `Proc` to ensure the specific `Proc` has been called as in other tests (by using `CountDownLatch` ).
> #665 AsyncFunc tests

- src/test/java/org/cactoos/io/TeeOutputTest.java
The problem in #683:
small coverage of `TeeOutput` class.
The solution:
added few unit tests to reach full coverage.
> #683 add unit tests to reach full coverage

- src/test/java/org/cactoos/func/RunnableOfTest.java
Issue https://github.com/yegor256/cactoos/issues/671.
In this pull request following constructors of RunnableOf are covered with tests to reach full coverage:
-  public RunnableOf(final Callable<X> proc)
-  public RunnableOf(final Proc<X> proc)
> #671 Cover RunnableOf with tests

- src/main/java/org/cactoos/matchers/TeeInputHasResult.java
- src/test/java/org/cactoos/io/TeeInputFromByteArrayTest.java
- src/test/java/org/cactoos/io/TeeInputFromBytesTest.java
- src/test/java/org/cactoos/matchers/TeeInputHasResultTest.java
It is for issue #721: adds a new matcher that checks result of TeeInput class: compares both TeeInput's results (direct and copied) to the expected value. As well this new matcher has been applied to existing tests of TeeInput class.
> #721: Add matcher for TeeInput class

- src/main/java/org/cactoos/io/TeeInput.java
- src/test/java/org/cactoos/io/TeeInputFromCharArrayTest.java
- src/test/java/org/cactoos/io/TeeInputFromCharSequenceTest.java
- src/test/java/org/cactoos/io/TeeInputFromFileTest.java
- src/test/java/org/cactoos/io/TeeInputFromInputTest.java
- src/test/java/org/cactoos/io/TeeInputFromPathTest.java
- src/test/java/org/cactoos/io/TeeInputFromReaderTest.java
- src/test/java/org/cactoos/io/TeeInputFromTextTest.java
- src/test/java/org/cactoos/io/TeeInputFromUriTest.java
- src/test/java/org/cactoos/io/TeeInputFromUrlTest.java
Pull request for #720: adds more unit tests for TeeInput class. But still, not all ctors are covered by tests as it would require more time and would produce a huge - non-reviewable - pull request.
> #720: Add more tests for TeeInput class.

- pom.xml
- src/test/java/org/cactoos/io/GzipOutputTest.java
- src/test/java/org/cactoos/io/InputOfTest.java
- src/test/java/org/cactoos/io/InputStreamOfTest.java
- src/test/java/org/cactoos/io/LoggingOutputTest.java
- src/test/java/org/cactoos/io/OutputStreamToTest.java
- src/test/java/org/cactoos/io/ReaderAsBytesTest.java
- src/test/java/org/cactoos/io/TeeOutputTest.java
- src/test/java/org/cactoos/io/WriterAsOutputStreamTest.java
- src/test/java/org/cactoos/io/WriterAsOutputTest.java
- src/test/java/org/cactoos/io/WriterToTest.java
For #702 
Replaced all temporary folder/files creation in tests with TemporaryFolders automatic removal of temporary data.
> #702 removing temporary files in tests

- src/test/java/org/cactoos/collection/MappedTest.java
- src/test/java/org/cactoos/collection/StickyCollectionTest.java
- src/test/java/org/cactoos/iterable/MappedTest.java
- src/test/java/org/cactoos/iterator/PartitionedTest.java
- src/test/java/org/cactoos/iterator/SyncIteratorTest.java
- src/test/java/org/cactoos/list/ListOfTest.java
- src/test/java/org/cactoos/list/MappedTest.java
- src/test/java/org/cactoos/list/StickyListTest.java
- src/test/java/org/cactoos/scalar/AndInThreadsTest.java
This is for this [issue](https://github.com/yegor256/cactoos/issues/769). There is still [one more](https://github.com/yegor256/cactoos/blob/b4223ce3e096424397e33058568b587844d93b24/src/main/java/org/cactoos/iterable/IterableOf.java#L50) left. I've created a [new issue](https://github.com/yegor256/cactoos/issues/773) for this one because it has a deeper problem that needs to be solved.
> replaced all Arrays.asList with new ListOf<>()

- src/main/java/org/cactoos/scalar/AvgOf.java
- src/main/java/org/cactoos/scalar/Folded.java
- src/main/java/org/cactoos/scalar/HighestOf.java
- src/main/java/org/cactoos/scalar/LowestOf.java
- src/main/java/org/cactoos/scalar/Reduced.java
- src/main/java/org/cactoos/scalar/SumOf.java
- src/test/java/org/cactoos/scalar/FoldedTest.java
- src/test/java/org/cactoos/scalar/ReducedTest.java
Resolution of #747, which states that 'Reduced' and 'Folded' are inverted. Swapped 'Reduced' and 'Folded' classes and test cases.
> Resolution of #747, "Reduced and Folded Confused"

- src/main/java/org/cactoos/io/HeadInput.java
- src/main/java/org/cactoos/io/HeadInputStream.java
- src/test/java/org/cactoos/io/HeadInputStreamTest.java
- src/test/java/org/cactoos/io/HeadInputTest.java
Pull request for issue #764.
- added new classes HeadInput and HeadInputStream
- added test cases to reach 83% of test coverage
> #764: Implement HeadInput

- src/main/java/org/cactoos/scalar/IoCheckedScalar.java
As asked in #766, `IoCheckedScalar` now uses `CheckedScalar` logic to return `IOException`.
> #766 Make IoCheckedScalar use CheckedScalar

- src/main/java/org/cactoos/Text.java
- src/main/java/org/cactoos/io/DigestEnvelope.java
- src/main/java/org/cactoos/scalar/SumOfDoubleScalar.java
- src/main/java/org/cactoos/scalar/SumOfFloatScalar.java
- src/main/java/org/cactoos/scalar/SumOfIntScalar.java
- src/main/java/org/cactoos/scalar/SumOfLongScalar.java
- src/main/java/org/cactoos/scalar/SumOfScalar.java
- src/main/java/org/cactoos/text/FormattedText.java
- src/main/java/org/cactoos/text/TextOf.java
Pull request for #781.
I've fixed all the issues defined in the ticket:
1. Use `UTF-8` as a default encoding for `TextOf(final InputStream input)` ctor.
2. Merge two `try` blocks.
3. Fix a link to `UncheckedText`.
4. Replace `new Object[this.args.size()]` with `new Object[0]`
5. Remove `serialVersionUID` from `SumOfDoubleScalar`, `SumOfFloatScalar`, `SumOfIntScalar`, `SumOfLongScalar` and `SumOfScalar`.
> #781: Fix a few code issues

- src/main/java/org/cactoos/scalar/And.java
- src/main/java/org/cactoos/scalar/AndInThreads.java
- src/main/java/org/cactoos/scalar/Or.java
Expanded javadoc for And/Or/AndInThreads for #692 
I've updated `And` and `Or` javadoc and added a link to `AndInThreads` which refers to `And` javadoc examples.
> #692 And/Or javadoc

- src/main/java/org/cactoos/io/TeeInputStream.java
- src/test/java/org/cactoos/io/GzipOutputTest.java
- src/test/java/org/cactoos/io/LoggingOutputTest.java
- src/test/java/org/cactoos/io/TeeInputStreamTest.java
- src/test/java/org/cactoos/io/WriterAsOutputStreamTest.java
- src/test/java/org/cactoos/io/WriterAsOutputTest.java
For #454 
**Problem**
`TeeInput` closes output stream after work.
**Solution**
I have replaced `close` with `flush` for output stream in `TeeInputStream.close()`
Valuable changes only in files: `TeeInputStream` and `TeeInputStreamTest`.
All other files just tests which had broken after the fix because they didn't close output stream explicitly.
> #454 TeeInput class should not close the OutputStream

- src/main/java/org/cactoos/iterable/IterableOfFloats.java
- src/main/java/org/cactoos/iterable/IterableOfLongs.java
- src/main/java/org/cactoos/iterator/IteratorOfFloats.java
- src/main/java/org/cactoos/iterator/IteratorOfInts.java
- src/test/java/org/cactoos/iterable/IterableOfFloatsTest.java
- src/test/java/org/cactoos/iterator/IteratorOfFloatsTest.java
- src/test/java/org/cactoos/iterator/IteratorOfIntsTest.java
#802 
- created `IteratorOfFloats` and `IteratorOfInts` and updated the appropriate Iterables
- added tests for those new classes
- added todo to continue implementation of longs and shorts
> #802 created iterator of floats and ints

- src/main/java/org/cactoos/scalar/CheckedScalar.java
- src/main/java/org/cactoos/scalar/FallbackFrom.java
- src/main/java/org/cactoos/scalar/InheritanceLevel.java
- src/main/java/org/cactoos/scalar/ScalarWithFallback.java
- src/test/java/org/cactoos/scalar/FallbackFromTest.java
- src/test/java/org/cactoos/scalar/InheritanceLevelTest.java
Pull request for #811.
I've changed the logic of InheritanceLevel.java so that it returns Integer.MIN_VALUE (instead of MAX_VALUE) when the classes are not related. As well I've fixed all dependencies which rely on this logic. And finally, I've fixed affected tests.
> #811: InheritanceLevel for unrelated classes should be negative

- src/test/java/org/cactoos/io/LoggingInputTest.java
This is for #776.
Basically, as the `Logger.getLogger()` method warns, if you don't retain a strong reference to a logger retrieved from this method, nothing prevent its garbage collection.
In this case, it meant the `Handler` we added was lost and so the test failed sometimes.
The solution:
- keep a (strong) reference to the logger during the whole test.
- use this reference to remove the handler.
- do NOT rely on the logger itself to create `LoggingInput` though (as this is the purpose of the test).
> Fix LoggingInputTest errors in appveyor

- src/main/java/org/cactoos/func/FuncWithFallback.java
- src/main/java/org/cactoos/scalar/FallbackFrom.java
- src/test/java/org/cactoos/func/FuncWithFallbackTest.java
This is for #821.
This:
- Replace the ad-hoc implementation of `FuncWithFallbacks` with use of `ScalarWithFallbacks`.
- Add more tests to `FuncWithFallbackTest` in order to cover the new extra behaviours of `FuncWithFallbacks`
- Rework some of the tests of `FuncWithFallbackTest` to be more object-oriented (less calls to static methods) and more precise (test equality instead of contains of `String`s)
- Add some more constructors to `FuncWithFallback` and `FallbackFrom` to write clearer/simpler tests.
>  FuncWithFallbacks uses ScalarWithFallbacks

- src/main/java/org/cactoos/iterable/IterableOfDoubles.java
- src/main/java/org/cactoos/iterable/IterableOfFloats.java
- src/main/java/org/cactoos/iterable/IterableOfInts.java
- src/main/java/org/cactoos/iterator/IteratorOfBytes.java
- src/main/java/org/cactoos/iterator/IteratorOfDoubles.java
- src/test/java/org/cactoos/iterator/IteratorOfBytesTest.java
- src/test/java/org/cactoos/iterator/IteratorOfDoublesTest.java
PR for #839.
- added IteratorOfBytes and IteratorOfDoubles
- added tests for new classes
- refactored implementation of IterableOfBytes and IterableOfDoubles so that they use new classes
- refactored IterableOfFloats and IterableOfInts: got rid of redundant UncheckedScalar wrapping
> #839: Introduce IteratorOfBytes and IteratorOfDoubles

- src/main/java/org/cactoos/collection/CollectionEnvelope.java
- src/main/java/org/cactoos/map/MapEnvelope.java
- src/test/java/org/cactoos/map/MapEnvelopeTest.java
Pull request for #844.
- implemented methods `equals` and `hashCode` for `MapEnvelope` class. Implementation depends on the entries of the map.
- added new test cases to cover implemented methods
- added a new puzzle to add equals/hashCode for CollectionEnvelope
> #844: Implement equals and hashCode for MapEnvelope

- src/main/java/org/cactoos/collection/Skipped.java
- src/main/java/org/cactoos/iterable/Skipped.java
- src/main/java/org/cactoos/iterator/Skipped.java
- src/test/java/org/cactoos/collection/SkippedTest.java
- src/test/java/org/cactoos/iterable/SkippedTest.java
- src/test/java/org/cactoos/iterator/SkippedTest.java
Pull request for #850 
I've restored skipped iterator, iterable and collection with small adjustments. As well related tests have been restored.
> #850: Resurrect skipped iterator, iterable and collection

- src/main/java/org/cactoos/list/ListEnvelope.java
- src/main/java/org/cactoos/list/ListIterator.java
- src/test/java/org/cactoos/list/ListEnvelopeTest.java
Pull request for #857 
I've implemented a new class `ListIterator` that forbids write operations: `set`, `add` and `remove`. This new iterator impl is used in the ListEnvelope only. As well added a few new test cases to improve test coverage.
> #857: Implement immutable ListIterator

- src/main/java/org/cactoos/collection/CollectionNoNulls.java
- src/main/java/org/cactoos/io/LoggingInputStream.java
- src/main/java/org/cactoos/io/LoggingOutputStream.java
- src/main/java/org/cactoos/iterator/IteratorNoNulls.java
- src/main/java/org/cactoos/list/ListNoNulls.java
- src/main/java/org/cactoos/map/MapEntry.java
- src/main/java/org/cactoos/map/MapNoNulls.java
- src/main/java/org/cactoos/scalar/AndInThreads.java
- src/main/java/org/cactoos/scalar/CheckedScalar.java
- src/test/java/org/cactoos/collection/CollectionNoNullsTest.java
- src/test/java/org/cactoos/func/ProcOfTest.java
- src/test/java/org/cactoos/io/TempFileTest.java
- src/test/java/org/cactoos/iterator/IteratorNoNullsTest.java
- src/test/java/org/cactoos/list/ListNoNullsTest.java
- src/test/java/org/cactoos/map/MapEntryTest.java
- src/test/java/org/cactoos/map/MapNoNullsTest.java
- src/test/java/org/cactoos/map/StickyMapTest.java
Pull request for #824.
All usages of `String.format` has been replaced with "FormattedText" (wrapped into "UncheckedText" when it's needed).
> #824: Use cactoos FormattedText instead of static String format.

- pom.xml
- src/test/java/org/cactoos/ProcTest.java
- src/test/java/org/cactoos/bytes/Base64BytesTest.java
- src/test/java/org/cactoos/bytes/BytesBase64Test.java
- src/test/java/org/cactoos/collection/BehavesAsCollection.java
- src/test/java/org/cactoos/collection/CollectionOfTest.java
- src/test/java/org/cactoos/collection/FilteredTest.java
- src/test/java/org/cactoos/collection/JoinedTest.java
- src/test/java/org/cactoos/collection/MappedTest.java
- src/test/java/org/cactoos/collection/ReversedTest.java
- src/test/java/org/cactoos/collection/ShuffledTest.java
- src/test/java/org/cactoos/collection/SkippedTest.java
- src/test/java/org/cactoos/collection/SolidCollectionTest.java
- src/test/java/org/cactoos/collection/StickyCollectionTest.java
- src/test/resources/forbidden-apis.txt
This is the first step toward more OO tests #588
- Introduce everything needed in Maven to forbid calls to static `Matchers`: for now it does not fail the build.
- Add `@todo` for continuing the work until everything is converted to pure OO
- This also ignore a test and add a `@todo` for a bug found in `CollectionOf`
> Tests are more OO 

- src/test/java/org/cactoos/collection/CollectionEnvelopeTest.java
- src/test/java/org/cactoos/iterable/IterableEnvelopeTest.java
> #862 Enforce immutability of IterableEnvelope through its iterator

- src/main/java/org/cactoos/collection/CollectionEnvelope.java
- src/main/java/org/cactoos/list/ListEnvelope.java
- src/test/java/org/cactoos/collection/CollectionEnvelopeTest.java
Introduced `equals` and `hashCode` in `CollectionEnvelope` for #881
> #881 equals and hashCode for CollectionEnvelope

- src/main/java/org/cactoos/map/MapEnvelope.java
Fix for #892 
- `equals()` of `MapEnvelope` refactored, just one return statement left
> #892, equals() of MapEnvelope refactored, just one return statement left

- src/main/java/org/cactoos/text/Base64Text.java
- src/main/java/org/cactoos/text/JoinedText.java
- src/main/java/org/cactoos/time/DateAsText.java
- src/main/java/org/cactoos/time/LocalDateAsText.java
- src/main/java/org/cactoos/time/LocalDateTimeAsText.java
- src/main/java/org/cactoos/time/OffsetDateTimeAsText.java
- src/main/java/org/cactoos/time/ZonedDateTimeAsText.java
- src/test/java/org/cactoos/time/DateAsTextTest.java
- src/test/java/org/cactoos/time/LocalDateAsTextTest.java
- src/test/java/org/cactoos/time/LocalDateTimeAsTextTest.java
- src/test/java/org/cactoos/time/OffsetDateTimeAsTextTest.java
- src/test/java/org/cactoos/time/ZonedDateTimeAsTextTest.java
this is for #897 
- all classes implementing `Text` were refactored to extend `TextEnvelope` in package `org.cactoos.time`
- unit tests have been adjusted in accordance with changes to classes implementing Text in package org.cactoos.time
- new puzzle has been created
> #897, classes implementing Text were refactored to extend TextEnvelope in package org.cactoos.time

- src/main/java/org/cactoos/func/TimedFunc.java
- src/test/java/org/cactoos/func/TimedFuncTest.java
For #887 
According to discussions in #886 and recommendations by ARC (https://github.com/yegor256/cactoos/pull/918#issuecomment-402320948), I simply removed the constructor using `null` and taking a `Proc`.
> Avoid usage of null value in TimedFunc

- pom.xml
- src/test/java/org/cactoos/map/BehavesAsMap.java
- src/test/java/org/cactoos/map/ClearDeletesAllValues.java
- src/test/java/org/cactoos/map/GroupedTest.java
- src/test/java/org/cactoos/map/MapEntryTest.java
- src/test/java/org/cactoos/map/MapEnvelopeTest.java
- src/test/java/org/cactoos/map/MapNoNullsTest.java
- src/test/java/org/cactoos/map/MapOfTest.java
- src/test/java/org/cactoos/map/PutAllUpdatesValues.java
- src/test/java/org/cactoos/map/PutUpdatesValues.java
- src/test/java/org/cactoos/map/RemoveDeletesValues.java
- src/test/java/org/cactoos/map/SolidMapTest.java
- src/test/java/org/cactoos/map/StickyMapTest.java
- src/test/java/org/cactoos/map/SyncMapTest.java
This is for #903.
I continued the work on migrating to OO matchers by doing the whole `map` package.
I also enabled the forbidden apis maven plugin only for this package and `bytes` (that was done for #588) so that we don't regress with time.
I updated the `@todo` so that work can continue.
> Use OO matchers instead of statics 

- README.md
Related issue #953 
/cc @llorllale @yegor256 
How it looks:
>  #953 - add gradle dependency info to readme

- src/main/java/org/cactoos/text/TextEnvelope.java
- src/test/java/org/cactoos/text/TextEnvelopeTest.java
For #942:
- Fixed `TextEnvelope.equals()` misbehavior;
- Fixed `TextEnvelopeTests` tests regarding `TextEnvelope.equals()`;
- Added puzzle for refactoring and making code more elegant.
> For #942: Fixed `TextEnvelope.equals()` misbehavior.

- src/main/java/org/cactoos/text/TextEnvelope.java
- src/test/java/org/cactoos/text/TextEnvelopeTest.java
I did not handle null in the equals method because it wasn't handle before. I am new to this project and to this way of coding, even if I road your two books, I am a bit disoriented.
I am a bit puzzle by the fact your linter does not accept variable namedLikeThat, would be happy to know why ?
Because previous code handle equals with object not being an instance of Text but there were no test, I added one.
About my Javadoc, I know it's not good, but I am not used to Javadoc my method especially when there are private (I think I name them and type them in a way they often don't need Javadoc).
Also, do you have a suggestion for a plugin for IDEA to run all your linter simply?
> # 955 Refactor text envelope equals

- src/main/java/org/cactoos/func/IoCheckedProc.java
Addresses issue #883.
Usage of null value is against design principles, see #861.
> Avoid usage of null value in IoCheckedProc.exec(X) #883

- .rultor.yml
This PR fixes #997:
* Now installing the `python-pip` package (containing the `pip` command) before installing `gitlint` using `pip`
> (#997) Fixed rultor merge build missing 'pip' command

- src/main/java/org/cactoos/package-info.java
- src/main/java/org/cactoos/scalar/package-info.java
- src/main/java/org/cactoos/set/package-info.java
- src/main/java/org/cactoos/text/Abbreviated.java
- src/main/java/org/cactoos/text/Base64Text.java
- src/main/java/org/cactoos/text/Sync.java
- src/main/java/org/cactoos/text/Synced.java
- src/main/java/org/cactoos/text/package-info.java
- src/main/java/org/cactoos/time/package-info.java
- src/test/java/org/cactoos/text/AbbreviatedTest.java
- src/test/java/org/cactoos/text/TextOfTest.java
This PR for #980  contains:
- 1 todo task for the renaming of Text(s)
- 1 todo task for the renaming of Scalar(s)
- 1 todo task for the renaming of Set(s)
- 1 todo task for the renaming of `org.cactoos.time` classes
- Renaming of few Text implementations
> #980 Avoid compound names for packages with scalar, set, text, and time

- src/main/java/org/cactoos/Func.java
- src/main/java/org/cactoos/Input.java
- src/main/java/org/cactoos/Scalar.java
- src/main/java/org/cactoos/Text.java
- src/main/java/org/cactoos/collection/CollectionNoNulls.java
- src/main/java/org/cactoos/iterable/Solid.java
- src/main/java/org/cactoos/scalar/NoNulls.java
- src/main/java/org/cactoos/text/NoNulls.java
- src/test/java/org/cactoos/ScalarTest.java
- src/test/java/org/cactoos/TextTest.java
This PR for #852 contains:
- 1 todo task for modification of Bytes, Input, Output
- 1 todo task for modification of Collection, Iterator (all others implementation of collections are already fixed)
- 1 todo task for modification of Proc, Func, BiFunc, BiProc
- Moved NoNulls for Scalar and Text, with fixes for their unit-tests and usage
> #852: Fix the NoNulls classes API inconsistency

- src/main/java/org/cactoos/collection/Skipped.java
- src/main/java/org/cactoos/iterable/Skipped.java
- src/test/java/org/cactoos/collection/SkippedTest.java
As described in #930 this API is not consistent. In both, collection.Skipped and iterable.Skipped first ctor argument is now always a skip (int).
> Consistent Skipped constructors API (#930)

- src/main/java/org/cactoos/text/Base64Decoded.java
- src/main/java/org/cactoos/text/Base64Encoded.java
- src/test/java/org/cactoos/text/Base64DecodedTest.java
- src/test/java/org/cactoos/text/Base64EncodedTest.java
As described in #1004. Two classes from text package were renamed.
- Base64Text to Base64Decoded as it encapsulates Base64 string and decode it
- Text64Base to Base64Encoded as it encapsulates any string and encode it to Base64
> #1004 Text: Base64 classes new names

- pom.xml
- src/test/java/org/cactoos/TextTest.java
- src/test/java/org/cactoos/io/BytesOfTest.java
- src/test/java/org/cactoos/io/HeadInputStreamTest.java
- src/test/java/org/cactoos/io/InputOfTest.java
- src/test/java/org/cactoos/io/InputWithFallbackTest.java
- src/test/java/org/cactoos/io/Md5DigestOfTest.java
- src/test/java/org/cactoos/io/OutputStreamToTest.java
- src/test/java/org/cactoos/io/Sha1DigestOfTest.java
- src/test/java/org/cactoos/io/Sha256DigestOfTest.java
- src/test/java/org/cactoos/io/StickyTest.java
- src/test/java/org/cactoos/io/TeeOutputTest.java
- src/test/java/org/cactoos/io/WriterAsOutputStreamTest.java
- src/test/java/org/cactoos/io/WriterAsOutputTest.java
- src/test/java/org/cactoos/io/WriterToTest.java
- src/test/java/org/cactoos/text/TextOfTest.java
As described in #1023. This was match harder than expected. I had to refactor many tests from io package, because there were many usage of 
`new TextHasString(
Matcher<>()
)`
which is no longer available in 0.13. In many places I have replaced MatcherAssert.assertThat() with Assertion<>() as I had to refactor tests anyways.  I know that there are too many changes, but without all of them code will not even compile.
Puzzle was left to replace usage of @Rule ExpectedException with Throws class.
> #1023 Update cactoos-matchers to 0.13

- src/main/java/org/cactoos/func/UncheckedProc.java
> Remove nulls from UncheckedProc #885

- src/main/java/org/cactoos/io/Joined.java
- src/test/java/org/cactoos/io/JoinedTest.java
This PR:
Regarding #1035
creates a constructor and adds a unit test for that
> (#1035) org.cactoos.io.Joined: add a Ctor of Iterable<Input>

- src/main/java/org/cactoos/func/IoCheckedBiProc.java
- src/main/java/org/cactoos/func/Retry.java
- src/test/java/org/cactoos/func/RetryTest.java
Solving #886 puzzle. According to recommendations by ARC (#918 ([comment](https://github.com/yegor256/cactoos/pull/918#issuecomment-402320948))), I simply removed the constructors using null and taking a Proc. Tests were modified as needed.
> Removed nulls from Retry (#886)

- src/main/java/org/cactoos/io/TempFolder.java
- src/test/java/org/cactoos/io/TempFolderTest.java
As described in #1022. New class for creating temporary directories was created. It is very similar to TempFile, but it can create directories only.
> #1022 TempFolder

- pom.xml
- src/main/java/org/cactoos/list/ListEnvelope.java
- src/main/java/org/cactoos/list/ListIteratorOf.java
- src/test/java/org/cactoos/list/ListEnvelopeTest.java
This PR:
Enables FindBugs (#891)  - 
Since external dependencies [are not allowed](https://github.com/yegor256/cactoos/pull/1020#issuecomment-457833335), the exclusion of the check can only be done on per-class basis in pom.xml
> (#891) findbugs should be enabled in qulice

- src/main/java/org/cactoos/io/TempFolder.java
- src/main/java/org/cactoos/text/Joined.java
- src/main/java/org/cactoos/text/Normalized.java
- src/main/java/org/cactoos/text/PaddedStartText.java
- src/main/java/org/cactoos/text/TextOf.java
- src/main/java/org/cactoos/text/Trimmed.java
- src/main/java/org/cactoos/text/package-info.java
- src/test/java/org/cactoos/io/AppendToTest.java
- src/test/java/org/cactoos/io/BytesOfTest.java
- src/test/java/org/cactoos/io/FakeHandler.java
- src/test/java/org/cactoos/iterable/ReversedTest.java
- src/test/java/org/cactoos/text/JoinedTest.java
- src/test/java/org/cactoos/text/NormalizedTest.java
- src/test/java/org/cactoos/text/TextEnvelopeTest.java
- src/test/java/org/cactoos/text/TextOfTest.java
- src/test/java/org/cactoos/text/TrimmedTest.java
As described in #1065. New naming convention was applied to Joined, Normalized and Trimmed. Puzzle were updated to continue.
> (#1065) Applied new naming convention in text package

- src/main/java/org/cactoos/func/Async.java
- src/test/java/org/cactoos/func/AsyncTest.java
#884 : this removes null from `Async` and also update tests to illustrate its usage with `Proc` and `FuncOf` (as proposed by ARC here: https://github.com/yegor256/cactoos/issues/551#issuecomment-386879090).
I also updated the rests to use `Assertion` while I was at it
> (#884) Remove nulls from Async class

- pom.xml
- src/test/java/org/cactoos/io/AppendToTest.java
- src/test/java/org/cactoos/io/HeadInputStreamTest.java
- src/test/java/org/cactoos/io/LoggingInputStreamTest.java
- src/test/java/org/cactoos/io/TeeOutputTest.java
- src/test/java/org/cactoos/io/WriterAsOutputStreamTest.java
- src/test/java/org/cactoos/io/WriterAsOutputTest.java
- src/test/java/org/cactoos/io/WriterToTest.java
- src/test/java/org/cactoos/io/package-info.java
- src/test/java/org/cactoos/scalar/BinaryTest.java
- src/test/java/org/cactoos/text/ReplacedTest.java
As described in #1064, sticky decorators were removed from io tests. In most of them TextOf and TextIs was replaced to InputOf and InputHasContent accordingly. It turns out that using `new TextOf(() -> input)` results in two calls to decorated input, which is the reason of tests failures.
> (#1064) Removed sticky decorators from io tests package

- src/main/java/org/cactoos/list/ListIteratorNoNulls.java
- src/main/java/org/cactoos/list/NoNulls.java
- src/test/java/org/cactoos/list/ListIteratorNoNullsTest.java
This if for #901.
This introduces a `ListIteratorNoNulls` that is immutable (via delegation to `ListIteratorOf`) and does not tolerate nulls.
Note that I reused most of the code from #1071 but simplified it in some places, not sure why the PR was closed...
> (#901) Null-free ListIterator in list.NoNulls

- src/main/java/org/cactoos/collection/CollectionEnvelope.java
- src/test/java/org/cactoos/collection/CollectionEnvelopeTest.java
This is for #917, there is not much in it, I also added a test which, even if not really needed in relation to the change, is not useless :)
> (#917) Improve performances of CollectionEnvelope equals

- src/main/java/org/cactoos/iterable/Skipped.java
- src/main/java/org/cactoos/iterable/Synced.java
- src/main/java/org/cactoos/iterator/Skipped.java
- src/main/java/org/cactoos/iterator/Synced.java
- src/main/java/org/cactoos/scalar/ItemAt.java
- src/test/java/org/cactoos/iterator/SkippedTest.java
- src/test/java/org/cactoos/iterator/SyncedTest.java
This is for #930.
While I was at it, I took care of the parameter order of Synced too and I updated the tests modified to use `Assertion`.
> (#930) Homogeneous constructor parameters for iter

- src/main/java/org/cactoos/time/DateOf.java
- src/test/java/org/cactoos/time/DateOfTest.java
This is for #949.
Added a test for the issue and implemented a solution based on https://stackoverflow.com/a/39685202/9046139
> (#949) DateOf now parses also date without time

- src/main/java/org/cactoos/map/MapEnvelope.java
- src/main/java/org/cactoos/scalar/EqualsNullable.java
- src/test/java/org/cactoos/map/MapEnvelopeTest.java
- src/test/java/org/cactoos/scalar/EqualsNullableTest.java
This is for (#922).
I update equals() and hashCode() to not fail with null values.
Also I updated tests which covered this fuctionality.
> (#922) equals() and hashCode() of MapEnvelope should be tolerant to nulls

- pom.xml
- src/main/java/org/cactoos/iterable/IterableEnvelope.java
- src/test/java/org/cactoos/iterable/IterableEnvelopeTest.java
- src/test/java/org/cactoos/iterable/IterableOfTest.java
PR for #1037 
I added equals() and hashCode() to IterableEnvelope.
> (#1037) Add equals and hashCode to IterableEnvelope

- src/test/java/org/cactoos/ScalarTest.java
- src/test/java/org/cactoos/TextTest.java
- src/test/java/org/cactoos/collection/NoNullsTest.java
- src/test/java/org/cactoos/iterator/NoNullsTest.java
- src/test/java/org/cactoos/map/MapEnvelopeTest.java
- src/test/java/org/cactoos/text/StrictTest.java
It updates the `TextTest` by using `Throws` matcher instead of `@Rule`-marked exception check.
> (#1039) Replaced @Rule with Throws matcher

- src/test/java/org/cactoos/map/BehavesAsMap.java
- src/test/java/org/cactoos/map/MapOfTest.java
- src/test/java/org/cactoos/map/SolidTest.java
- src/test/java/org/cactoos/map/StickyTest.java
- src/test/java/org/cactoos/map/SyncedTest.java
This is for #927 
Updated matchers inside BehavesAsMap.matchesSafely().
Updated tests which uses BehavesAsMap.
> (#927) What is the expected behaviour of BehavesAsMap?

- src/main/java/org/cactoos/collection/CollectionEnvelope.java
- src/main/java/org/cactoos/list/ListEnvelope.java
- src/main/java/org/cactoos/list/ListIteratorOf.java
- src/main/java/org/cactoos/list/Mapped.java
- src/test/java/org/cactoos/list/ListEnvelopeTest.java
- src/test/java/org/cactoos/list/MappedTest.java
This is for #996:
- made `ListEnvelope` public and clarified doc on its behaviour
- Ensured `subList` was returning a `List` with the same behaviour (note that it means sublist is now called lazily)
- Added some tests for this
- Prevented overriding of `toString` and simplified `Mapped` as a result
> (#996) Make ListEnvelope public and consolidate API

- src/main/java/org/cactoos/func/CallableOf.java
- src/test/java/org/cactoos/func/CallableOfTest.java
This is for #1040.
I had to rework `CallableOf` implementation to avoid the need for `null` and remove the constructor that was using it. Now a `Proc` or a `Func` must always be accompanied by an input to be transformed into a `Callable`.
> (#1040) Remove null from CallableOf constructor

- pom.xml
- src/test/java/org/cactoos/experimental/ThreadsTest.java
PR for #1112:
* Speed up ThreadsTest by shortening sleep durations, reducing number of threads, and deleting an unnecessary test  (this shaved off ~20s in my tests)
* Stop recompiling all source files due to [bug](https://issues.apache.org/jira/browse/MCOMPILER-209) in maven-compiler-plugin (this shaved off ~10s in my tests, now "only" recompiles 14 files for some reason)
* Left puzzle to continue speeding up `mvn test`
Duration after above changes (the timing keeps varying and is not all that reliable):
```
llorllale:~/dev/java/cactoos$ time mvn test
...lots of stuff...
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ cactoos ---
[INFO] Compiling 14 source files to /home/llorllale/dev/java/cactoos/target/classes
... lots of stuff...
Tests run: 1196, Failures: 0, Errors: …
```
> (#1112) Speed up unit tests

- src/main/java/org/cactoos/text/Abbreviated.java
- src/main/java/org/cactoos/text/FormattedText.java
This is for #1063 
I replaced implementing Text with extending TextEnvelope and moved logic from asString to constructor.
> (#1063) All classes implementing Text need to be refactored to extend TextEnvelope

- src/main/java/org/cactoos/io/package-info.java
- src/test/java/org/cactoos/TextTest.java
- src/test/java/org/cactoos/io/LSInputOfTest.java
- src/test/java/org/cactoos/io/TeeInputFromReaderTest.java
- src/test/java/org/cactoos/io/TeeInputFromUriTest.java
- src/test/java/org/cactoos/io/TeeInputFromUrlTest.java
This is for #1033.
I replaced some of the `MatcherAssert#assertThat` usages with `Assertion` from cactoos-matchers. There is still a lot code to replace - I added a `@todo` for that.
> (#1033) Replace use of MatcherAssert.assertThat with Assertion from cactoos-matchers

- pom.xml
- src/test/java/org/cactoos/collection/BehavesAsCollection.java
- src/test/java/org/cactoos/collection/CollectionEnvelopeTest.java
- src/test/java/org/cactoos/collection/CollectionOfTest.java
- src/test/java/org/cactoos/collection/FilteredTest.java
- src/test/java/org/cactoos/collection/HeadOfTest.java
- src/test/java/org/cactoos/collection/JoinedTest.java
- src/test/java/org/cactoos/collection/MappedTest.java
- src/test/java/org/cactoos/collection/ReversedTest.java
- src/test/java/org/cactoos/collection/ShuffledTest.java
- src/test/java/org/cactoos/collection/SkippedTest.java
- src/test/java/org/cactoos/collection/SolidTest.java
- src/test/java/org/cactoos/collection/SortedTest.java
- src/test/java/org/cactoos/collection/StickyTest.java
- src/test/java/org/cactoos/collection/SyncedTest.java
- src/test/java/org/cactoos/collection/TailOfTest.java
This is for #1082 
I replaced forbidden API calls in org.cactoos.collection package, updated to-do.
> (#1082) Replace forbidden API calls

- src/test/java/org/cactoos/io/GzipInputTest.java
- src/test/java/org/cactoos/io/GzipOutputTest.java
This if for #1048 
I replaced data bytes with simple numbers
> (#1048) Refactor GzipInput and GzipOutput tests to be more readable

- src/main/java/org/cactoos/map/Merged.java
- src/test/java/org/cactoos/map/MergedTest.java
This is for #1084 
I added Merged extends MapEnvelope implementation and tests for it
> (#1084) Merged/Joined - allows to merge/join several java.util.Properties

- src/main/java/org/cactoos/text/FormattedText.java
- src/main/java/org/cactoos/text/NoNulls.java
- src/main/java/org/cactoos/text/Randomized.java
- src/main/java/org/cactoos/text/Synced.java
This is for #1116.
I've applied the new pattern for 3 classes and added a todo to continue the work.
> (#1116) Extends TextEnvelope when possible

- src/main/java/org/cactoos/collection/CollectionEnvelope.java
- src/main/java/org/cactoos/collection/Mapped.java
- src/test/java/org/cactoos/collection/MappedTest.java
This is for #1109: it makes `CollectionEnvelope.toString` final and simplify `Mapped` in the process.
In order for `Mapped` to be simplified, I had to align some of its behaviour with all the other classes of cactoos in the `collection` package (which all delegate to the equivalent `Iterable` implementation of the same behaviour).
I had to remove one of the tests that was making a very strange assumption about it: I believe it was a test that made no sense since it wasn't really testing the expected behaviour of `Mapped` but something about its implementation.
> (#1109) Make CollectionEnvelope.toString final and fix Mapped

- src/main/java/org/cactoos/scalar/ItemAt.java
- src/test/java/org/cactoos/iterable/CycledTest.java
- src/test/java/org/cactoos/iterator/CycledTest.java
- src/test/java/org/cactoos/scalar/ItemAtTest.java
This is for #1095, it always put the iterable/iterator last in the constructor
While doing so I:
- removed duplicate constructors
- added extra constructors for simpler fallback and position
- removed constructors taking `Iterator` since I am also assigned #1104 (it's less work to do so than doing both separated, and it's easier to review too).
Note that I had to replace the `T` type with a `Scalar<T>` for `fallback` in one constructor to avoid confusion between position and fallback in the two-parameters constructors (in particular when applying to an `Iterable<Integer>`)
An alternative would be to remove all constructor not taking a position (which would make complete sense IMHO).
> (#1095) ItemAt always takes the iterable/iterator last

- src/test/java/org/cactoos/experimental/ThreadsTest.java
- src/test/java/org/cactoos/iterable/SolidTest.java
- src/test/java/org/cactoos/iterator/SyncedTest.java
This is for #1115.
One more step toward faster tests.
After manually testing the robustness of `RunsInThreads` (using the same method as https://www.yegor256.com/2018/03/27/how-to-test-thread-safety.html), I established that in `org.cactoos.iterable.SolidTest` there was a lot of overlapping threads and thus the number of loops could be reduced.
The results are not so good in `org.cactoos.iterator.SyncedTest` so I added a todo with instruction on how to improve things.
On my machine (2 cpus), before:
```
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.567 sec - in org.cactoos.iterable.SolidTest
```
After:
```
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.721 sec - in org.cactoos.iterable.SolidTest
```
> (#1115) Speed up more tests

- src/main/java/org/cactoos/iterator/Immutable.java
- src/test/java/org/cactoos/iterator/ImmutableTest.java
This is for #1102 
As discussed in the issue, `toString()` implementation for `Immutable` should be delegated to its inner iterator.
> (#1102) toString() implementation for Immutable iterator

- src/main/java/org/cactoos/io/OutputTo.java
This is for #1143.
There isn't much to say, the issue description already analyzes the problem in detail and suggests a solution. I agree, and applied the simple fix.
I see no way to correctly unit test this, since it would require the creation of a file from a relative path consisting only of the filename, and of course we would want to put such file in a temporary directory, like we do for other tests. However, it seems that [there is no reliable way to accomplish this](https://stackoverflow.com/questions/840190/changing-the-current-working-directory-in-java).
> (#1143) Using getAbsoluteFile() to fix error for single filename files

- pom.xml
- src/test/java/org/cactoos/list/BehavesAsList.java
- src/test/java/org/cactoos/list/JoinedTest.java
- src/test/java/org/cactoos/list/ListOfTest.java
- src/test/java/org/cactoos/list/MappedTest.java
- src/test/java/org/cactoos/list/ShuffledTest.java
- src/test/java/org/cactoos/list/SolidTest.java
- src/test/java/org/cactoos/list/SortedTest.java
- src/test/java/org/cactoos/list/StickyTest.java
This is for #1119. I haven't add the list package to the includes of the plugin because there is is still the `MatcherAssert` static to be migrated to `Assertion`.
> (#1119) Remove static matchers from list

- src/test/java/org/cactoos/iterator/SyncedTest.java
This is for #1141.  I made 10 attempts to check the problem with SyncedTest.java and always I had average time less than 10 seconds.
```
Tests run: 1193, Failures: 0, Errors: 0, Skipped: 2
Running org.cactoos.iterator.SyncedTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.59 sec - in org.cactoos.iterator.SyncedTest
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.797 s
[INFO] Finished at: 2019-07-13T11:21:54+07:00
[INFO] ------------------------------------------------------------------------
```
You can check the time in Travis pipeline build. The task was not relevant. I removed todo from class description.
> (#1141): Continued speeding up the `mvn test` in SyncedTest.java

- src/main/java/org/cactoos/scalar/FirstOf.java
This is for #1137. I replaced params `Func<T, Boolean> cond` and `Iterable<T> src` to `Filtered<T>` in `FirstOf<>()` constructor, and ofcourse fixed tests.
> (#1137) Simplified responsibility and implementation of FirstOf

- .travis.yml
This is a fix to #1172.
Just a quick fix without migration to OpenJDK builds.
> (#1172) Added `dist: trusty` to fix broken Travis build

- src/main/java/org/cactoos/io/package-info.java
- src/test/java/org/cactoos/io/DirectoryTest.java
- src/test/java/org/cactoos/io/HeadInputStreamTest.java
- src/test/java/org/cactoos/io/HeadInputTest.java
- src/test/java/org/cactoos/io/InputAsBytesTest.java
- src/test/java/org/cactoos/io/InputOfTest.java
- src/test/java/org/cactoos/io/package-info.java
This is for #1152.
I created the new todo for continuing into the `package-info.java` file in tests since it made more sense.
> (#1152) Remove some more static Matcher asserts

- src/test/java/org/cactoos/iterator/NoNullsTest.java
PR for https://github.com/yegor256/cactoos/issues/1106.
Removed the `@Rule` with `Throws`, because it can match exception messages now, and simplified tests.
> (#1106) Replaced @Rule with Throws and simplified tests

- pom.xml
For #1151 
- qulice update to fix build errors
- leave a puzzle to fix all files don't pass in the updated qulice
- we should fix them and remove from `pom.xml`
> (#1151) qulice update to fix build errors

- README.md
This is for #1186.
Compared to what was proposed in the ticket:
- removed extraneous useless options
- add `--interactive` to stop container on ctrl+C
- use `maven:3-jdk-8` image instead of `yegor/java8`, which is one of the worst image I have ever seen ;) (it weight 3.6Gi, and has something like 20 layers).
- do the build in one go
> (#1186) Add Makefile to run build in Docker

- src/main/java/org/cactoos/iterator/IteratorEnvelope.java
- src/main/java/org/cactoos/iterator/Sliced.java
This is for #1193: as discussed with ARC [here](https://github.com/yegor256/cactoos/issues/1193#issuecomment-536208067), this introduces an `IteratorEnvelope` to ease implementation of `Iterator`s by delegation.
> (#1193) Introduce IteratorEnvelope

- pom.xml
- src/test/java/org/cactoos/io/OutputStreamToTest.java
- src/test/java/org/cactoos/io/OutputToTest.java
- src/test/java/org/cactoos/io/ReaderAsBytesTest.java
- src/test/java/org/cactoos/io/ReaderOfTest.java
- src/test/java/org/cactoos/io/package-info.java
This is for #1182 
I had to increment cactoos-matchers version to benefit from bugfixes (llorllale/cactoos-matchers#132) that were preventing tests to pass with `Assertion`.
> (#1182) Remove some more static call to assert

- src/test/java/org/cactoos/iterator/IteratorOfTest.java
This pull request is for issue [1222](https://github.com/yegor256/cactoos/issues/1222)
According to the article https://www.yegor256.com/2016/05/03/test-methods-must-share-nothing.html
the test methods must not share any methods or data.
> (#1222) Fixed test methods sharing issue

- src/main/java/org/cactoos/list/ListIteratorOf.java
- src/main/java/org/cactoos/list/package-info.java
- src/test/java/org/cactoos/list/ListEnvelopeTest.java
- src/test/java/org/cactoos/list/ListIteratorNoNullsTest.java
- src/test/java/org/cactoos/list/NoNullsTest.java
This PR is for [1230](https://github.com/yegor256/cactoos/issues/1230)
The [ListIteratorOf](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/list/ListIteratorOf.java) should support mutability, if the origin supports
> (#1230) ListIteratorOf can be mutable and immutable, depending on origin

- src/main/java/org/cactoos/set/SetOf.java
- src/test/java/org/cactoos/set/SetOfTest.java
This pull request is for issue [1212](https://github.com/yegor256/cactoos/issues/1212)
`org.cactoos.set.SetOf` was causing an issue when the original collection/array contained duplicate values, which resulted the cut off of the collection just right after first duplicated value.
> (#1212) Fixed SetOf, which discarded all elements after duplicated occurrence

- README.md
This PR is for issue [1246](https://github.com/yegor256/cactoos/issues/1246).
This includes an additional documentation description for [SetOf](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/set/SetOf.java).
> README documentation for SetOf was added

- src/main/java/org/cactoos/collection/Immutable.java
- src/main/java/org/cactoos/iterator/Immutable.java
- src/main/java/org/cactoos/list/Immutable.java
- src/test/java/org/cactoos/list/ImmutableTest.java
This is for #1236 
Following discussion with ARC, it was decided that `Immutable` should only decorate and not introduce behaviour or internal state.
I took the liberty of applying the same to `list` and `iterator` since there was not so much to do just for `collection`.
I removed extra constructors as they are out of scope of the responsibility of an immutable decorator.
> (#1236) Immutable decorators are just simple decorators

- src/main/java/org/cactoos/list/Joined.java
- src/main/java/org/cactoos/list/ListEnvelope.java
- src/main/java/org/cactoos/list/ListOf.java
- src/main/java/org/cactoos/list/Mapped.java
- src/main/java/org/cactoos/list/Shuffled.java
- src/main/java/org/cactoos/list/Solid.java
- src/main/java/org/cactoos/list/Sorted.java
- src/main/java/org/cactoos/list/Sticky.java
- src/main/java/org/cactoos/list/Synced.java
- src/test/java/org/cactoos/func/ForEachInThreadsTest.java
- src/test/java/org/cactoos/list/ImmutableTest.java
- src/test/java/org/cactoos/list/ListEnvelopeTest.java
- src/test/java/org/cactoos/list/ListIteratorOfTest.java
- src/test/java/org/cactoos/list/StickyTest.java
- src/test/java/org/cactoos/scalar/AndInThreadsTest.java
This is for #1185.
I had to remove the unmodifiable wrapper in `Sticky` for things to work as expected. This is coherent with work planned in #1233 to remove them from all `List` implementations.
I also simplified the constructors of the `List` implementations since `List` and `Collection` implements `Iterable`.
> (#1185) List Envelope is just an envelope

- src/main/java/org/cactoos/io/HeadOf.java
- src/test/java/org/cactoos/io/HeadOfTest.java
This is for #1239, as per discussed with ARC, we rename `HeadInput` to `HeadOf` to homogenize naming.
> (#1239) HeadInput is renamed to HeadOf

- src/test/java/org/cactoos/collection/JoinedTest.java
This is for #1218 
Resolved puzzle `898-4936d4fd`
Updated class `org.cactoos.collection.JoinedTest` to remove reference to `Collections.emptyList()` static method reference.
> (#1218) Replaced Collections.emptyList with ListOf

- .rultor.yml
For #1288: fixes for no-rdoc and no-ri options
> For #1288: fixes for no-rdoc and no-ri options

- README.md
- src/main/java/org/cactoos/set/Sorted.java
- src/test/java/org/cactoos/set/SortedTest.java
> (#1259) Sorted Set with custom comparator

- src/main/java/org/cactoos/set/SetOf.java
- src/main/java/org/cactoos/set/Sorted.java
- src/main/java/org/cactoos/set/package-info.java
This is for #1292. 
I also did Sorted since it seemed a good idea and there wasn't much work.
I'm not clear why I had to ignore `PMD.ConstructorOnlyInitializesOrCallOtherConstructors` though while it is not needed for `ListOf` or `SetOf`... !
> (#1292) SetOf and Sorted are real in memory sets

- src/main/java/org/cactoos/set/Sorted.java
- src/main/java/org/cactoos/set/SortedSetEnvelope.java
- src/test/java/org/cactoos/set/SortedTest.java
PR for https://github.com/yegor256/cactoos/issues/1325
`Sorted` now implements `SortedSet`.
> #1325 - Sorted now implements SortedSet.

- .rultor.yml
- pom.xml
For #1346: fixing sonar execution
- added sonar configurations to `pom.xml`
- configured sonar to run on rultor merges
> For #1346: fixing sonar execution

- src/test/java/org/cactoos/io/TeeInputFromCharArrayTest.java
- src/test/java/org/cactoos/io/TeeInputFromCharSequenceTest.java
- src/test/java/org/cactoos/io/TeeInputFromTextTest.java
- src/test/java/org/cactoos/io/package-info.java
- src/test/java/org/cactoos/scalar/package-info.java
- src/test/java/org/cactoos/set/BehavesAsSet.java
- src/test/java/org/cactoos/text/AbbreviatedTest.java
- src/test/java/org/cactoos/text/Base64DecodedTest.java
- src/test/java/org/cactoos/text/Base64EncodedTest.java
- src/test/java/org/cactoos/text/FormattedTextTest.java
- src/test/java/org/cactoos/text/HexOfTest.java
- src/test/java/org/cactoos/text/IsBlankTest.java
- src/test/java/org/cactoos/text/StrictTest.java
- src/test/java/org/cactoos/text/TextEnvelopeTest.java
- src/test/java/org/cactoos/text/TextOfTest.java
1343
- Changed calling static method _MatcherAssert.assertThat_ for **Assertion** object
- Remove unused imports after that
- _copiesFromCharSequenceToPath_ method was the duplicates of _copiesFromCharSequenceToFile_
and I've changed it, now it calls what it supposed to call.
> 1343 - replacing static MatcherAssert.assertThat with Assertion object

- src/main/java/org/cactoos/iterator/Reversed.java
- src/test/java/org/cactoos/iterator/ReversedTest.java
> #1337: Tests Iterator Reverse

- src/main/java/org/cactoos/iterable/IterableOf.java
- src/main/java/org/cactoos/iterable/Matched.java
- src/test/java/org/cactoos/iterable/IterableOfTest.java
- src/test/java/org/cactoos/iterable/MatchedTest.java
#1308
Fixed the problem when two Iterates of different sizes returned the wrong result on method equals.
> 1308 fixed IterableOf.equals and add required tests

- src/main/java/org/cactoos/scalar/ScalarWithFallback.java
- src/test/java/org/cactoos/scalar/ScalarWithFallbackTest.java
This pull-request has no corresponding issue.
What's changed:
* Added extra constructors for `ScalarWithFallback` class.
* New constructors were covered by unit-tests.
> ScalarWithFallback: extra ctors were added

- src/test/java/org/cactoos/scalar/BoolOfTest.java
- src/test/java/org/cactoos/scalar/ConstantTest.java
- src/test/java/org/cactoos/scalar/DivisionOfTest.java
- src/test/java/org/cactoos/scalar/EqualsTest.java
- src/test/java/org/cactoos/scalar/FirstOfTest.java
- src/test/java/org/cactoos/scalar/FoldedTest.java
- src/test/java/org/cactoos/scalar/HashCodeTest.java
- src/test/java/org/cactoos/scalar/package-info.java
> #1367: Scalar - Replacing usage of MatcherAssert.assertThat

- .rultor.yml
For #1346: forcing delete of settings.xml at the end of merging
> For #1346: forcing delete of settings.xml at the end of merging

- src/test/java/org/cactoos/scalar/HashCodeTest.java
- src/test/java/org/cactoos/scalar/InheritanceLevelTest.java
- src/test/java/org/cactoos/scalar/RetryTest.java
- src/test/java/org/cactoos/scalar/package-info.java
> #1376: Scalar - Replace all the IsEqual with ScalarHashValue

- src/test/java/org/cactoos/scalar/EqualityTest.java
- src/test/java/org/cactoos/scalar/FallbackFromTest.java
- src/test/java/org/cactoos/scalar/FalseTest.java
- src/test/java/org/cactoos/scalar/IoCheckedTest.java
- src/test/java/org/cactoos/scalar/package-info.java
> Remove some more MatcherAssert

- src/main/java/org/cactoos/RepeatedProc.java
- src/test/java/org/cactoos/RepeatedProcTest.java
- src/test/java/org/cactoos/experimental/TimedTest.java
For #1277 
Introduced  `RepeatedProc`
> For #1277: Add RepeatedProc

- pom.xml
- src/test/java/org/cactoos/map/NoNullsTest.java
> (#1411) Cleanup pom, bump parent and add todo for junit 5

- src/main/java/org/cactoos/func/ForEachWithIndex.java
- src/test/java/org/cactoos/func/ForEachWithIndexTest.java
There was no ticket for this, but I wanted it, and it seemed to be within the scope of the overarching objectives of the library. It's my way of donating without money to give.
I copied `ForEach` and modified it to use `BiFunc`, `BiProc`, and `AndWithIndex` to give us a `ForEachWithIndex`. I also copied the `ForEachTest` and modified it to ensure the class behaves as expected.
Tests passed locally.
> Added a ForEachWithIndex class

- src/test/java/org/cactoos/io/TeeInputFromInputTest.java
- src/test/java/org/cactoos/io/TeeInputFromUriTest.java
Per #1395 
- Fix `TeeInputFromInputTest` tests to check file content
- Fix `TeeInputFromUriTest` tests to check message content
- Remove puzzle
> #1395: Fix TeeInput tests to check file content

- pom.xml
- src/test/java/org/cactoos/func/ProcOfTest.java
- src/test/java/org/cactoos/func/RepeatedTest.java
- src/test/java/org/cactoos/func/SolidBiFuncTest.java
- src/test/java/org/cactoos/func/SolidFuncTest.java
- src/test/java/org/cactoos/func/StickyBiFuncTest.java
- src/test/java/org/cactoos/func/StickyFuncTest.java
- src/test/java/org/cactoos/func/SyncFuncTest.java
- src/test/java/org/cactoos/func/TimedFuncTest.java
- src/test/java/org/cactoos/func/UncheckedBiFuncTest.java
Per #1223: 
- Replace static methods with objects
- Update puzzle
> (#1223) Replace static factory methods with direct call to new

- src/main/java/org/cactoos/iterable/Matched.java
- src/main/java/org/cactoos/iterator/Partitioned.java
- src/main/java/org/cactoos/list/Immutable.java
- src/test/resources/forbidden-apis.txt
Per #1220 
- Replace with `Immutable`
- Add to `forbidden-apis.txt`
> #1220: Replace usage of Collections.unmodifableList with org.cactoos.list.Immutable

- .rultor.yml
- pom.xml
Final touch for #1411.
New rultor config comes from succeeding in a releasing a new version of cactoos-matchers and upgrading jcabi-parent allows to remove useless config in the pom.
> Rultor config + latest jcabi-parent

- src/test/java/org/cactoos/list/ImmutableTest.java
- src/test/java/org/cactoos/list/ListEnvelopeTest.java
Per #1217:  
- Replace tests which check for `UnsupporterOperationException`
- Move `Immutable` related tests to `ImmutableTest`
> #1217: Refactor test for ListEnvelope

- src/main/java/org/cactoos/text/Abbreviated.java
- src/main/java/org/cactoos/text/Base64Encoded.java
- src/main/java/org/cactoos/text/FormattedText.java
- src/main/java/org/cactoos/text/HexOf.java
- src/main/java/org/cactoos/text/Joined.java
- src/main/java/org/cactoos/text/Lowered.java
- src/main/java/org/cactoos/text/NoNulls.java
- src/main/java/org/cactoos/text/Normalized.java
- src/main/java/org/cactoos/text/PaddedStart.java
- src/main/java/org/cactoos/text/PrefixOf.java
- src/main/java/org/cactoos/text/Randomized.java
- src/main/java/org/cactoos/text/Repeated.java
- src/main/java/org/cactoos/text/Replaced.java
- src/main/java/org/cactoos/text/Reversed.java
- src/main/java/org/cactoos/text/Rotated.java
- src/main/java/org/cactoos/text/Strict.java
- src/main/java/org/cactoos/text/Sub.java
- src/main/java/org/cactoos/text/SuffixOf.java
- src/main/java/org/cactoos/text/SwappedCase.java
- src/main/java/org/cactoos/text/Synced.java
- src/main/java/org/cactoos/text/TextEnvelope.java
- src/main/java/org/cactoos/text/TextOf.java
- src/main/java/org/cactoos/text/Trimmed.java
- src/main/java/org/cactoos/text/TrimmedLeft.java
- src/main/java/org/cactoos/text/TrimmedRight.java
- src/main/java/org/cactoos/text/Upper.java
- src/test/java/org/cactoos/text/TextEnvelopeTest.java
- src/test/java/org/cactoos/text/TextOfTest.java
> (#1287) TextEnvelope is a real envelope

- src/main/java/org/cactoos/text/UncheckedText.java
- src/test/java/org/cactoos/text/UncheckedTextTest.java
Per #1280 :
- Implements `#toString()` in `UncheckedText`
- Implements a test to check this functionality
> #1280: UncheckedText should implement toString()

- src/main/java/org/cactoos/text/Capitalized.java
- src/test/java/org/cactoos/text/CapitalizedTest.java
Added EO version of StringUtils.capitalize
I hope for your understanding, this is my first pull request to open source project.
Signed-off-by: kokodyn <kokodyn@gmail.com>
> Added Capitalized

- src/main/java/org/cactoos/scalar/AvgOf.java
- src/main/java/org/cactoos/scalar/Ternary.java
- src/test/java/org/cactoos/scalar/TernaryTest.java
This is for #1475.
I've also fixed a test that looked very fishy.
> (#1475) Make Ternary consistent over its evaluation

- pom.xml
This is for #1417, jacoco was only enabled with qulice while the ci expects them to be there when running only tests.
> (#1417) always run jacoco

- src/main/java/org/cactoos/text/Lowered.java
- src/main/java/org/cactoos/text/Mapped.java
- src/main/java/org/cactoos/text/Replaced.java
- src/main/java/org/cactoos/text/Reversed.java
- src/main/java/org/cactoos/text/Strict.java
- src/main/java/org/cactoos/text/Sub.java
- src/main/java/org/cactoos/text/SwappedCase.java
- src/main/java/org/cactoos/text/Trimmed.java
- src/main/java/org/cactoos/text/TrimmedLeft.java
- src/main/java/org/cactoos/text/TrimmedRight.java
- src/main/java/org/cactoos/text/Upper.java
- src/test/java/org/cactoos/text/MappedTest.java
Per #1462 
- Add `text.Mapped`
- Use it where applicable
> For #1462: Introduce text.Mapped

- src/main/java/org/cactoos/io/BytesOf.java
- src/main/java/org/cactoos/iterable/IterableOfBytes.java
- src/main/java/org/cactoos/iterable/IterableOfChars.java
- src/main/java/org/cactoos/iterator/IteratorOfBytes.java
- src/test/java/org/cactoos/io/BytesOfTest.java
There is no ticket for this.
I noticed that IterableOfBytes was broken because it would reuse the same iterator each time.
I also fixed the constructor order and made `BytesOf(Iterable)` be lazy.
> Cleanup fix iterable/iterator of bytes

- src/main/java/org/cactoos/BiProc.java
- src/main/java/org/cactoos/proc/ForEach.java
- src/main/java/org/cactoos/proc/ForEachInThreads.java
- src/main/java/org/cactoos/proc/ForEachWithIndex.java
- src/main/java/org/cactoos/proc/ProcOf.java
- src/main/java/org/cactoos/scalar/And.java
- src/main/java/org/cactoos/scalar/AndInThreads.java
- src/main/java/org/cactoos/scalar/AndWithIndex.java
- src/main/java/org/cactoos/scalar/Or.java
- src/test/java/org/cactoos/func/BiFuncOfTest.java
- src/test/java/org/cactoos/func/FuncOfTest.java
- src/test/java/org/cactoos/io/TempFolderTest.java
- src/test/java/org/cactoos/proc/ProcOfTest.java
- src/test/java/org/cactoos/proc/RunnableOfTest.java
- src/test/java/org/cactoos/scalar/AndInThreadsTest.java
- src/test/java/org/cactoos/scalar/RepeatedTest.java
- src/test/java/org/cactoos/scalar/ScalarOfTest.java
Some more changes for #1445. I took this opportunity to cleanup and improve test coverage
> 1445 scalarof

- src/main/java/org/cactoos/scalar/Flattened.java
- src/main/java/org/cactoos/scalar/Folded.java
- src/main/java/org/cactoos/scalar/HighestOf.java
- src/main/java/org/cactoos/scalar/LowestOf.java
- src/main/java/org/cactoos/scalar/Reduced.java
This is related to #1533, I need it for #1335 but I'm dedicating a PR to it.
> (#1533) More variance on some generics

- src/main/java/org/cactoos/iterable/Paged.java
- src/main/java/org/cactoos/iterator/Paged.java
- src/test/java/org/cactoos/iterable/PagedTest.java
- src/test/java/org/cactoos/iterator/PagedTest.java
#1464 
- create `iterator.Paged`
- refactor `iterable.Paged`
- remove checkstyle suppression in `iterable.Paged`
> #1464 Add iterator.Paged and remove checkstyle suppression

- src/main/java/org/cactoos/func/BiFuncEnveloppe.java
- src/main/java/org/cactoos/func/BiFuncOf.java
- src/main/java/org/cactoos/func/SolidBiFunc.java
- src/main/java/org/cactoos/proc/ProcEnvelope.java
- src/main/java/org/cactoos/proc/RunnableEnvelope.java
- src/main/java/org/cactoos/scalar/CallableEnvelope.java
- src/main/java/org/cactoos/scalar/CallableOf.java
#1526
- Introduce envelope for Proc, BiFunc, Callable and Runnable
- simplify the code of ProcOf and BiFuncOf etc  by extending their envelope
> (#1526) For consistency sake with func

- src/main/java/org/cactoos/BiProc.java
- src/main/java/org/cactoos/proc/BiProcEnvelope.java
- src/main/java/org/cactoos/proc/BiProcOf.java
- src/test/java/org/cactoos/proc/BiProcOfTest.java
- src/test/java/org/cactoos/scalar/AndWithIndexTest.java
#1532
- Introduce BiProcOf and some tests
- Use BiProcOf in AndWithIndexTest
> (#1532) Introduce BiProcOf on the model of FuncOf, etc.

- pom.xml
- src/main/java/org/cactoos/io/TempFolder.java
- src/main/java/org/cactoos/text/Capitalized.java
- src/main/java/org/cactoos/text/PaddedStart.java
- src/test/java/org/cactoos/bytes/BytesOfTest.java
- src/test/java/org/cactoos/bytes/HexOfTest.java
- src/test/java/org/cactoos/collection/BehavesAsCollection.java
- src/test/java/org/cactoos/collection/ImmutableTest.java
- src/test/java/org/cactoos/func/AsyncTest.java
- src/test/java/org/cactoos/func/BiFuncOfTest.java
- src/test/java/org/cactoos/func/FuncOfTest.java
- src/test/java/org/cactoos/io/AppendToTest.java
- src/test/java/org/cactoos/io/InputOfTest.java
- src/test/java/org/cactoos/io/StickyTest.java
- src/test/java/org/cactoos/io/TempFileTest.java
- src/test/java/org/cactoos/iterable/JoinedTest.java
- src/test/java/org/cactoos/iterator/NoNullsTest.java
- src/test/java/org/cactoos/list/BehavesAsList.java
- src/test/java/org/cactoos/list/ImmutableTest.java
- src/test/java/org/cactoos/proc/BiProcOfTest.java
- src/test/java/org/cactoos/proc/ForEachInThreadsTest.java
- src/test/java/org/cactoos/proc/ProcOfTest.java
- src/test/java/org/cactoos/proc/RunnableOfTest.java
- src/test/java/org/cactoos/scalar/AndInThreadsTest.java
- src/test/java/org/cactoos/scalar/AndWithIndexTest.java
- src/test/java/org/cactoos/scalar/PropertiesOfTest.java
- src/test/java/org/cactoos/scalar/ScalarOfTest.java
- src/test/java/org/cactoos/text/TextOfTest.java
- src/test/java/org/cactoos/text/UncheckedTextTest.java
Bump cactoos-matchers to latest version, use `Verifies` instead of `MatcherOf` and replace `Joined` by `Concatenated` when possible.
> (#1531) Bump cactoos-matchers to 0.24

- src/main/java/org/cactoos/map/Merged.java
- src/test/java/org/cactoos/map/MergedTest.java
> #1549: Add ctor to map.Merged

- src/main/java/org/cactoos/list/Joined.java
- src/main/java/org/cactoos/list/JoinedListIterator.java
- src/test/java/org/cactoos/list/JoinedListIteratorTest.java
For #1254
- Implements `JoinedListIterator`
- Introduces unit tests for `JoinedListIterator`
> (#1254) Implements ListIteratorJoined

- src/main/java/org/cactoos/bytes/CheckedBytes.java
- src/main/java/org/cactoos/bytes/UncheckedBytes.java
- src/main/java/org/cactoos/collection/package-info.java
- src/main/java/org/cactoos/experimental/package-info.java
- src/main/java/org/cactoos/func/package-info.java
- src/main/java/org/cactoos/io/package-info.java
- src/main/java/org/cactoos/iterable/package-info.java
- src/main/java/org/cactoos/iterator/package-info.java
- src/main/java/org/cactoos/list/package-info.java
- src/main/java/org/cactoos/map/package-info.java
- src/main/java/org/cactoos/proc/package-info.java
- src/main/java/org/cactoos/scalar/Checked.java
- src/main/java/org/cactoos/scalar/package-info.java
- src/main/java/org/cactoos/set/package-info.java
- src/main/java/org/cactoos/text/package-info.java
- src/main/java/org/cactoos/time/package-info.java
- src/test/java/org/cactoos/scalar/CheckedTest.java
For #1533
- Use generic variance in package bytes as explained in #1533
> (#1533) Exploit generic variance in package bytes

- pom.xml
- src/test/java/org/cactoos/bytes/BytesOfTest.java
- src/test/java/org/cactoos/bytes/InputAsBytesTest.java
- src/test/java/org/cactoos/collection/BehavesAsCollection.java
- src/test/java/org/cactoos/io/InputOfTest.java
- src/test/java/org/cactoos/map/BehavesAsMap.java
- src/test/java/org/cactoos/map/MapOfTest.java
- src/test/java/org/cactoos/map/NoNullsTest.java
- src/test/java/org/cactoos/map/RemoveDeletesValues.java
- src/test/java/org/cactoos/scalar/TernaryTest.java
- src/test/java/org/cactoos/set/SetOfTest.java
- src/test/java/org/cactoos/text/AbbreviatedTest.java
This was missing from #1411 to actually use hamcrest 2.2 instead of the old one from junit dependencies
> (#1411) Actually use latest hamcrest 2.2

- pom.xml
- src/test/java/org/cactoos/io/DeadOutputTest.java
- src/test/java/org/cactoos/io/InputStreamOfTest.java
- src/test/java/org/cactoos/io/LSInputOfTest.java
- src/test/java/org/cactoos/io/LoggingInputTest.java
- src/test/java/org/cactoos/io/LoggingOutputTest.java
- src/test/java/org/cactoos/io/ResourceOfTest.java
- src/test/java/org/cactoos/io/TailOfTest.java
- src/test/java/org/cactoos/io/TeeInputStreamTest.java
- src/test/java/org/cactoos/io/TeeOutputStreamTest.java
- src/test/java/org/cactoos/io/TempFileTest.java
For #1434 :
- Replace calls to `Matchers` for test package `com.cactoos.io`
> (#1434) Replace calls to Matchers with their OO counterparts

- pom.xml
- src/test/java/org/cactoos/BytesTest.java
- src/test/java/org/cactoos/bytes/HexOfTest.java
- src/test/java/org/cactoos/bytes/ReaderAsBytesTest.java
- src/test/java/org/cactoos/bytes/UncheckedBytesTest.java
For #1453. Migrate tests to JUnit 5 for test packages :
- `org.cactoos`
- `org.cactoos.bytes`
- `org.cactoos.collection`
- `org.cactoos.experimental`
> (#1453) Migrate test to JUnit 5

- src/test/java/org/cactoos/io/InputOfTest.java
Per #1443 
- Remove TrustManager & SSLContext initiazliation from test
> (#1443) Remove redundant tests for SSL

- src/main/java/org/cactoos/scalar/Or.java
This is just one class of #1569, I need it for https://github.com/llorllale/cactoos-matchers/issues/240.
> (#1569) Exploit generic variance for Or

- src/main/java/org/cactoos/io/ResourceOf.java
- src/main/java/org/cactoos/io/TempFile.java
- src/main/java/org/cactoos/text/SuffixOf.java
- src/test/java/org/cactoos/TextTest.java
- src/test/java/org/cactoos/io/GzipInputTest.java
- src/test/java/org/cactoos/io/InputOfTest.java
- src/test/java/org/cactoos/io/InputStreamOfTest.java
- src/test/java/org/cactoos/io/TempFileTest.java
- src/test/java/org/cactoos/iterable/MappedTest.java
- src/test/java/org/cactoos/text/TextEnvelopeTest.java
- src/test/java/org/cactoos/text/TextOfTest.java
- Avoid calling `asString`
Releated to https://github.com/llorllale/cactoos-matchers/issues/199
> Use `IsText` for testing `Text` objects

- src/main/java/org/cactoos/iterable/IterableOf.java
- src/main/java/org/cactoos/map/MapEnvelope.java
- src/main/java/org/cactoos/text/TextOf.java
- src/test/java/org/cactoos/map/MapEnvelopeTest.java
- src/test/java/org/cactoos/text/TextOfTest.java
For #1560:
- Constructor `TextOf(Iterator)` now delegates to `TextOf(Iterable)`
- Constructor `TextOf` parameter is typed as `Iterable<Character>` instead of `Iterable<?>`
- Add extra test for `TextOf(Iterable)`
- Replace usages of `TextOf(Iterable<?>)` with `Joined` and `Concatenated`
> (#1560) Delegate `TextOf(Iterator)` to `TextOf(Iterable)`

- src/main/java/org/cactoos/func/FuncWithFallback.java
- src/main/java/org/cactoos/func/package-info.java
- src/main/java/org/cactoos/scalar/ScalarWithFallback.java
For #1572:
- Generify `ScalarWithFallback` (generify this class since `FuncWithFallback` depends on it)
- Generify `FuncWithFallback`
Now fallbacks for `ScalarWithFallback` and `FuncWithFallback` can produce object derived types from given original type.
```java
Fallback<Long> longOnNoFile = new Fallback.From<>(FileNotFoundException.class, _t -> 0L);
Fallback<Double> doubleOnIo = new Fallback.From<>(IOException.class, _t -> 0.0);
Fallback<Integer> intOtherwise = new Fallback.From<>(Exception.class, _t -> 0);
Func<String, Number> readFileLength = new FuncOf<>(fileName -> {
throw new IOException("Access denied. You can't read file " + fileName);
});
FuncWithFallback<String, Number> safeReadFileLength =
new FuncWithFallback<String, Number>(
readFileLength,
longOnNoFile,
doubleOnIo, …
```
> (#1572) Covariance for `func.FuncWithFallback`

- src/main/java/org/cactoos/func/FuncOf.java
- src/main/java/org/cactoos/func/Repeated.java
- src/main/java/org/cactoos/proc/BiProcEnvelope.java
- src/main/java/org/cactoos/proc/BiProcNoNulls.java
- src/main/java/org/cactoos/proc/BiProcOf.java
- src/main/java/org/cactoos/proc/ProcEnvelope.java
- src/main/java/org/cactoos/proc/ProcNoNulls.java
- src/main/java/org/cactoos/proc/ProcOf.java
- src/main/java/org/cactoos/proc/RepeatedProc.java
- src/main/java/org/cactoos/proc/package-info.java
For #1567:
Generify incoming parameters (use `? super T`) for next classes:
- `ProcOf`, `ProcEnvelope` and `FuncOf`
- `ProcNoNulls`
- `BiProcOf` and `BiProcEnvelope`
- `BiProcNoNulls`
- `RepeatedProc` and `Repeated`
> (#1567) Generify `org.cactoos.proc` package

- src/main/java/org/cactoos/iterator/IteratorEnvelope.java
- src/main/java/org/cactoos/iterator/NoNulls.java
- src/main/java/org/cactoos/iterator/Shuffled.java
- src/main/java/org/cactoos/iterator/Skipped.java
- src/main/java/org/cactoos/iterator/Sliced.java
- src/main/java/org/cactoos/iterator/Sorted.java
- src/main/java/org/cactoos/iterator/Synced.java
For #1565:
Add covariant constructor params for
- `IteratorEnvelope`
- `Synced`
- `Sorted`
- `Skipped`
- `Sliced`
- `Shuffled`
- `NoNulls`
> (#1565) Improve generic variance for `org.cactoos.iterator`

- src/main/java/org/cactoos/text/Abbreviated.java
- src/main/java/org/cactoos/text/Flattened.java
- src/main/java/org/cactoos/text/FormattedText.java
- src/main/java/org/cactoos/text/Joined.java
- src/main/java/org/cactoos/text/Mapped.java
- src/main/java/org/cactoos/text/Replaced.java
- src/main/java/org/cactoos/text/Split.java
- src/main/java/org/cactoos/text/Strict.java
- src/main/java/org/cactoos/text/Sub.java
- src/main/java/org/cactoos/text/UncheckedText.java
- src/main/java/org/cactoos/text/package-info.java
- src/test/java/org/cactoos/text/StrictTest.java
- src/test/java/org/cactoos/text/SubTest.java
For #1574:
- Use `CharSequence` instead of `String` when possible
- Generic covariance for `Flattened`
- Wildcards for `Collection` if type parameter doesn't matter
- Counter-variance for `Func`
> (#1574) Generify `org.cactoos.text`

- src/main/java/org/cactoos/collection/Immutable.java
- src/main/java/org/cactoos/collection/NoNulls.java
- src/main/java/org/cactoos/collection/package-info.java
- src/test/java/org/cactoos/collection/NoNullsTest.java
For #1575.
Generify parameter types in constructors of org.cactoos.collection package classses:
- Immutable
- NoNulls
It's done by using unchecked casts, because there are absolutely no other ways to achive this, due to JDK interfaces limitations.
> (#1575) Generify `org.cactoos.collection` package

- src/main/java/org/cactoos/iterable/IterableOf.java
- src/main/java/org/cactoos/iterable/Joined.java
- src/main/java/org/cactoos/iterable/NoNulls.java
- src/main/java/org/cactoos/iterable/Partitioned.java
- src/main/java/org/cactoos/iterable/RangeOf.java
- src/main/java/org/cactoos/iterable/Repeated.java
- src/main/java/org/cactoos/iterable/Shuffled.java
- src/main/java/org/cactoos/iterable/Skipped.java
- src/main/java/org/cactoos/iterable/Sliced.java
- src/main/java/org/cactoos/iterable/package-info.java
For #1568.
Generify parameter types in constructors of `org.cactoos.iterable` package classses:
- IterableOf
- Joined
- NoNulls
- Partitioned
- RangeOf
- Repeated
- Shuffled
- Skipped
- Sliced
> (#1568) Generify org.cactoos.iterable package

- src/main/java/org/cactoos/experimental/package-info.java
For #1573.
- Generified parameter types in constructors of `org.cactoos.experimental.Threads` class
- Removed `todo` comment
Actually one class and one constructor, which contract, in my opinion, could be `relaxed`.
> (#1573) Generify `org.cactoos.experimental` package. 

- src/main/java/org/cactoos/list/Immutable.java
- src/main/java/org/cactoos/list/ImmutableListIterator.java
- src/main/java/org/cactoos/list/Joined.java
- src/main/java/org/cactoos/list/JoinedListIterator.java
- src/main/java/org/cactoos/list/package-info.java
- src/test/java/org/cactoos/list/JoinedListIteratorTest.java
For #1566:
Generify some classes in org.cactoos.list package:
- org.cactoos.list.Immutable
- org.cactoos.list.ImmutableListIterator
- org.cactoos.list.Joined
- org.cactoos.list.JoinedListIterator
> (#1566) Generify org.cactoos.list package

- README.md
According to issue #1670, I compiled and ran the code examples in `README.md`. Some of them didn't compile or crashed with an exception, so I fixed them
> Fixed examples in readme.md

- src/main/java/org/cactoos/scalar/ThrowsOnFalse.java
- src/test/java/org/cactoos/scalar/ThrowsOnFalseTest.java
@victornoel take a look, please
it's a squashed of #1692 
closes #1175
> Throw on false

- src/main/java/org/cactoos/scalar/Strict.java
- src/test/java/org/cactoos/scalar/StrictTest.java
Added `Strict` scalar, that encapsulates another scalar, a rule for validating that original scalar, and an exception, that is thrown in case the original value doesn't meet the rule.
> Add Strict for Scalar

- src/test/java/org/cactoos/io/InputOfTest.java
- src/test/java/org/cactoos/io/StickyTest.java
> URI instead of URL

- src/main/java/org/cactoos/text/Sub.java
- src/test/java/org/cactoos/text/SubTest.java
Closes #1717
@yegor256 please review and consider merging it, thanks!
> Feat: add support for negative value to get tail from the string

- src/main/java/org/cactoos/bytes/BytesOf.java
This Pull Request improves the Javadoc documentation for the `BytesOf` class. The changes include:
- Detailed descriptions of constructors and methods.
- Clearer explanations of parameters and return values.
- Examples of usage for better understanding.
These improvements aim to make the codebase more maintainable and easier to understand for developers. Feedback and suggestions are welcome.
> Improved Javadoc for BytesOf class

- src/main/java/org/cactoos/TriFunc.java
- src/main/java/org/cactoos/func/BiFuncSplitPreserve.java
- src/main/java/org/cactoos/func/TriFuncSplitPreserve.java
- src/main/java/org/cactoos/text/SplitPreserveAllTokens.java
- src/test/java/org/cactoos/text/SplitPreserveTest.java
Rationale of some decisions made:
1) Functional Interface allows use of custom String splitter function avoiding the static method calls
2) A new class created as modifying already existing Split class would not be shorter : if we add some checking for flags would create just as many constructors as with 2 distinct classes
3) Tests only compare lengths of obtained Collections
>  Adding an OOP analogue for StringUtils.splitPreserveAllTokens ISSUE #1722

- src/test/java/org/cactoos/list/JoinedListIteratorTest.java
Added tests for the `JoinedListIterator` class.
One of the tests I wanted to add was the following:
```java
@Test  
void previousIndexTest() {  
final ListIterator<Integer> joined = new JoinedListIterator<>(  
new ListOf<>(1).listIterator(),  
new ListOf<>(2).listIterator(),  
new ListOf<>(3).listIterator()  
);  
joined.next();  
new Assertion<>(  
"Must return index of the previous element",  
joined.previousIndex(),  
new IsEqual<>(0)  
).affirm();  
joined.next();
new Assertion<>(  
"Must return index of the previous element",  
joined.previousIndex(),  
new IsEqual<>(1)  
).affirm();  
}
```
Surprisingly, the test failed. Currently, the `previousIndex()` method returns `-1` for the first call and `0` for the second call, which contradicts the expected behavior. My suspision is that …
> Improve JoinedListIterator code coverage

- src/main/java/org/cactoos/list/JoinedListIterator.java
- src/test/java/org/cactoos/list/JoinedListIteratorTest.java
Fixed an off by one error mentioned in #1762. Added test to ensure correct behavior.
> Fix previousIndex method in JoinedListIterator

- src/test/java/org/cactoos/iterable/SortedTest.java
Noticed that all tests for `iterable\Sorted.java` use the wrong `hasItems()` checker that doesn't care about the ordering of the items. The correct checker in this case is `contains()`.
> Fix sorted iterable tests

- src/main/java/org/cactoos/iterator/Sliced.java
- src/test/java/org/cactoos/iterator/SlicedTest.java
This PR fixes an issue with the `Sliced` iterator class where the second constructor was using an incorrect end predicate.
The current implementation uses `any -> !iterator.hasNext()` which captures the iterator's state at construction time. This creates a fixed boolean value that doesn't change when the actual `hasNext()` method is called later, leading to incorrect iteration behavior.
Changed the predicate to `any -> false` which means "never end because of the predicate". The actual end condition is properly checked in the `hasNext()` method with `this.iterator.hasNext()`.
Fixes #[issue-number]
> Fix incorrect end predicate in Sliced iterator's second constructor

- src/main/java/org/cactoos/set/Diff.java
- src/test/java/org/cactoos/set/DiffTest.java
```markdown
This PR introduces a new `Diff<T>` class that computes the set difference operation (A - B) between two sets. The class extends `SetEnvelope<T>` and provides multiple constructors to support different input types:
- Iterable<T>
- Iterator<T>
- Scalar<Iterable<T>>
- SetOf<T>
The implementation follows the Cactoos object-oriented approach and includes comprehensive test coverage.
- The `Diff` class computes elements that are in the first set but not in the second set
- Added multiple constructors to support various input types
- Implemented a private `computeDiff` method to handle the actual set difference operation
- Added thorough test cases covering various scenarios:
- Basic set difference
- Empty set handling (both first and second sets)
- Working with java.util.Set
- …
```
> Add Diff<T> class for computing set differences

- src/main/java/org/cactoos/text/AbbreviatedLeft.java
- src/main/java/org/cactoos/text/AbbreviatedRight.java
- src/test/java/org/cactoos/text/AbbreviatedLeftTest.java
- src/test/java/org/cactoos/text/AbbreviatedRightTest.java
This PR introduces a new `AbbreviatedLeft` class that complements the existing `Abbreviated` class by providing text abbreviation functionality from the left side.
Features
Abbreviates text by adding ellipses (...) at the beginning when text exceeds the maximum width
Preserves original text when it's shorter than or equal to the maximum width
Provides the same constructors and behavior as the existing `Abbreviated` class
Includes comprehensive test coverage
**Example Usage**:
```
// Abbreviates to "...over the lazy dog" when max width is 20
String abbreviated = new AbbreviatedLeft(
"The quick brown fox jumps over the lazy dog", 
20
).asString();
```
This implementation follows the same object-oriented principles as the rest of the cactoos library and maintains the same quality standards.
> Add AbbreviatedLeft class to abbreviate text from the left side

- src/main/java/org/cactoos/map/MapDiff.java
- src/test/java/org/cactoos/map/MapDiffTest.java
This PR introduces a new `MapDiff` class that allows computing the difference between two maps. The implementation follows the functional programming principles of Cactoos.
Features
Computes the difference between two maps (entries in the first map that are not in the second map)
Supports various input types:
Maps
Iterables of `Map.Entry`
Iterators of `Map.Entry`
Scalar suppliers of `Iterables`
Implementation Details
`MapDiff` extends `MapEnvelope` to maintain the immutability principle
The difference is computed by removing all keys from the first map that exist in the second map
Comprehensive test coverage ensures correct behavior with different input types and edge cases
Testing
The implementation includes tests for:
Basic map difference computation
Empty map handling (both as first …
> Implement MapDiff class for map difference operations

- src/main/java/org/cactoos/set/Union.java
- src/test/java/org/cactoos/set/UnionTest.java
This PR adds a new `Union` class to the  package that represents the union of two sets. The implementation follows the same pattern as the existing Diff class.
The Union class:
Extends `SetEnvelope<T>`
Provides constructors for various input types (iterables, iterators, scalar suppliers)
Includes a private static method to compute the union of two sets
Is fully tested with various scenarios including empty sets, Java's built-in sets, and collections
This implementation complements the existing set operations in the library and follows the same design principles.
> Add Union class for set operations

- .vscode/settings.json
- src/main/java/org/cactoos/set/Diff.java
- src/main/java/org/cactoos/set/Intersection.java
- src/test/java/org/cactoos/set/DiffTest.java
- src/test/java/org/cactoos/set/IntersectionTest.java
This PR adds a new `Intersection` class to the cactoos library that provides set intersection functionality. The implementation follows the same pattern as the existing `Diff` class.
- Implements set intersection operation (elements common to both sets)
- Provides multiple constructors to handle different input types:
- Iterable
- Iterator
- Scalar
- SetOf
- Includes comprehensive test coverage
The `Intersection` class extends `SetEnvelope<T>` and uses Java's `retainAll` method to compute the intersection between two sets. This approach is consistent with the existing `Diff` class implementation.
The test class includes tests for:
- Basic intersection functionality
- Intersection with empty sets
- Intersection with Java's built-in Set implementation
- Intersection with iterables and …
> Implement Set Intersection functionality

- src/main/java/org/cactoos/exception/RootCause.java
- src/main/java/org/cactoos/exception/package-info.java
- src/main/java/org/cactoos/iterable/IterableOfStackTrace.java
- src/main/java/org/cactoos/iterator/IteratorOfStackTrace.java
- src/test/java/org/cactoos/exception/RootCauseTest.java
- src/test/java/org/cactoos/exception/package-info.java
- src/test/java/org/cactoos/iterable/IterableOfStackTraceTest.java
- src/test/java/org/cactoos/iterator/IteratorOfStackTraceTest.java
@yegor256 Please review.
Implementation of 
https://github.com/yegor256/cactoos/issues/1715
Missing analog for ExceptionUtils:
The most useful thing to get rootCause Exception.
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/exception/ExceptionUtils.html
> Implementation of an analogue for ExceptionUtils.getRootCause
