yegor256/cactoos

- README.md
add Checkstyle checks list link
> add Checkstyle info into README.md

- .travis.yml
- README.md
- pom.xml
Test coverage badge on README page
> Test coverage

- src/main/java/org/cactoos/io/ResourceAsInput.java
- src/main/java/org/cactoos/text/FormattedText.java
- src/test/java/org/cactoos/text/FormattedTextTest.java
- rename Sprintf to FormattedText
- add unit test
> Sprintf rename

- src/main/java/org/cactoos/Func.java
- src/main/java/org/cactoos/list/FilteredIterable.java
- src/main/java/org/cactoos/list/FilteredIterator.java
As per https://github.com/yegor256/cactoos/issues/30
`Func.Pred` introduced
> #30 Predication

- README.md
- src/main/java/org/cactoos/text/ArrayAsBytes.java
- src/main/java/org/cactoos/text/BytesAsText.java
- src/main/java/org/cactoos/text/ThrowableAsBytes.java
- src/test/java/org/cactoos/io/FileAsInputTest.java
- src/test/java/org/cactoos/io/TeeInputTest.java
- src/test/java/org/cactoos/io/UrlAsInputTest.java
- src/test/java/org/cactoos/text/BytesAsTextTest.java
- src/test/java/org/cactoos/text/ThrowableAsBytesTest.java
as per #46 
* Added `ThrowableAsBytes`
* Removed `InputAsText`
* Added `InputAsBytes`
* Added `BytesAsText`
> #46: ThrowableAsBytes

- src/main/java/org/cactoos/Func.java
- src/main/java/org/cactoos/func/FuncWithCallback.java
- src/main/java/org/cactoos/func/RunnableAsProc.java
- src/test/java/org/cactoos/func/FuncWithCallbackTest.java
- src/test/java/org/cactoos/func/package-info.java
as per #50 
* `FuncWithCallback` introduced
> #50: FuncWithCallback

- src/main/java/org/cactoos/list/Repeat.java
- src/test/java/org/cactoos/list/RepeatTest.java
`Repeat` iterable to repeat some element multiple times.
> Repeat iterable

- src/main/java/org/cactoos/ScalarHasValue.java
- src/main/java/org/cactoos/func/FuncAsMatcher.java
- src/main/java/org/cactoos/io/BytesAsInput.java
- src/main/java/org/cactoos/text/EmptyBytes.java
- src/main/java/org/cactoos/text/TextAsBytes.java
- src/test/java/org/cactoos/func/FuncWithCallbackTest.java
- src/test/java/org/cactoos/io/FileAsInputTest.java
- src/test/java/org/cactoos/io/InputAsBytesTest.java
- src/test/java/org/cactoos/io/LengthOfInputTest.java
- src/test/java/org/cactoos/io/ResourceAsInputTest.java
- src/test/java/org/cactoos/io/TeeInputTest.java
- src/test/java/org/cactoos/io/UrlAsInputTest.java
- src/test/java/org/cactoos/list/AllOfTest.java
- src/test/java/org/cactoos/list/AnyOfTest.java
- src/test/java/org/cactoos/list/ConcatenatedIterableTest.java
- src/test/java/org/cactoos/list/FilteredIterableTest.java
- src/test/java/org/cactoos/list/FirstOfTest.java
- src/test/java/org/cactoos/list/IterableAsListTest.java
- src/test/java/org/cactoos/list/RepeatTest.java
- src/test/java/org/cactoos/list/TransformedIterableTest.java
- src/test/java/org/cactoos/text/BytesAsTextTest.java
- src/test/java/org/cactoos/text/FormattedTextTest.java
- src/test/java/org/cactoos/text/IsBlankTest.java
- src/test/java/org/cactoos/text/TextAsBytesTest.java
- src/test/java/org/cactoos/text/ThrowableAsBytesTest.java
- src/test/java/org/cactoos/text/TrimmedTextTest.java
- src/test/java/org/cactoos/text/UpperTextTest.java
as per #66 
* `FuncAsMatcher` added
* reasons added to all test methods
> 66: side effect testing

- .travis.yml
- src/main/java/org/cactoos/Func.java
- src/main/java/org/cactoos/FuncApplies.java
- src/main/java/org/cactoos/func/AlwaysTrueFunc.java
- src/main/java/org/cactoos/func/CallableAsFunc.java
- src/main/java/org/cactoos/func/FuncAsCallable.java
- src/main/java/org/cactoos/func/FuncAsRunnable.java
- src/main/java/org/cactoos/func/RunnableAsFunc.java
- src/main/java/org/cactoos/func/UncheckedFunc.java
- src/main/java/org/cactoos/list/FilteredIterable.java
- src/main/java/org/cactoos/list/FilteredIterator.java
- src/main/java/org/cactoos/list/IterableAsBoolean.java
- src/main/java/org/cactoos/list/IterableAsBooleans.java
- src/main/java/org/cactoos/list/TransformedIterator.java
- src/main/java/org/cactoos/package-info.java
- src/test/java/org/cactoos/func/ConstFuncTest.java
- src/test/java/org/cactoos/func/FuncAsCallableTest.java
- src/test/java/org/cactoos/func/FuncAsRunnableTest.java
- src/test/java/org/cactoos/func/UncheckedFuncTest.java
- src/test/java/org/cactoos/list/AllOfTest.java
as per #70 
* `Func` redesigned
* `FuncApplies`
* `UncheckedFunc`
* many other changes
> 70: func redesigned

- src/main/java/org/cactoos/io/PathAsInput.java
- src/main/java/org/cactoos/io/PathAsOutput.java
- src/test/java/org/cactoos/io/TeeInputTest.java
> #24: PathAsInput and PathAsOutput

- src/main/java/org/cactoos/text/ReplacedText.java
- src/test/java/org/cactoos/text/ReplacedTextTest.java
> Replaced Text

- src/main/java/org/cactoos/text/ReversedText.java
- src/test/java/org/cactoos/text/ReversedTextTest.java
> Reverse The Text

- src/main/java/org/cactoos/ScalarHasValue.java
- src/main/java/org/cactoos/TextHasString.java
- src/main/java/org/cactoos/func/IoCheckedFunc.java
- src/main/java/org/cactoos/func/IoCheckedProc.java
- src/main/java/org/cactoos/func/IoCheckedScalar.java
- src/main/java/org/cactoos/func/StickyScalar.java
- src/main/java/org/cactoos/func/UncheckedFunc.java
- src/main/java/org/cactoos/func/UncheckedScalar.java
- src/main/java/org/cactoos/io/ResourceAsInput.java
- src/main/java/org/cactoos/list/IterableAsList.java
- src/test/java/org/cactoos/io/ResourceAsInputTest.java
as in #92 
* `ResourceAsInput` got extra `Func` argument
* `IoCheckedFunc` added
* `IoCheckedProc` added
* `IoCheckedScalar` added
> #92: ResourceAsInput with extra argument

- src/main/java/org/cactoos/func/SyncFunc.java
- src/main/java/org/cactoos/func/SyncProc.java
- src/main/java/org/cactoos/func/SyncScalar.java
as in #94 
* `SyncFunc` introduced
* `SyncProc` introduced
* `SyncScalar` introduced
> #94: Sync primitives

- src/main/java/org/cactoos/list/IterableAsList.java
- src/main/java/org/cactoos/text/FormattedText.java
> #96 Change pattern to Text in FormattedText.

- src/main/java/org/cactoos/func/IoCheckedFunc.java
- src/test/java/org/cactoos/func/IoCheckedFuncTest.java
- src/test/java/org/cactoos/func/IoCheckedProcTest.java
- src/test/java/org/cactoos/func/IoCheckedScalarTest.java
as per #102: `IoCheckedFunc` fixed
> 102: IoCheckedFunc fixed

- README.md
- src/test/java/org/cactoos/text/ReplacedTextTest.java
- src/test/java/org/cactoos/text/ReversedTextTest.java
- src/test/java/org/cactoos/text/TextAsBoolTest.java
- src/test/java/org/cactoos/text/TextAsDoubleTest.java
- src/test/java/org/cactoos/text/TextAsFloatTest.java
- src/test/java/org/cactoos/text/TextAsIntTest.java
- src/test/java/org/cactoos/text/TextAsLongTest.java
- src/test/java/org/cactoos/text/TrimmedTextTest.java
Improve unit tests - add missing cases.
> Improve unit tests

- src/main/java/org/cactoos/map/IterableAsMap.java
- src/main/java/org/cactoos/map/package-info.java
- src/test/java/org/cactoos/map/IterableAsMapTest.java
- src/test/java/org/cactoos/map/package-info.java
> #116: IterableAsMap

- src/main/java/org/cactoos/io/TeeInputStream.java
- src/test/java/org/cactoos/io/TeeInputStreamTest.java
as per #121: bug in `TeeInputStream` fixed
> #121: bug in TeeInputStream fixed

- src/main/java/org/cactoos/io/InputAsBytes.java
- src/main/java/org/cactoos/io/TeeInputStream.java
- src/test/java/org/cactoos/io/InputAsBytesTest.java
as per #123: bug in `InputAsBytes` fixed
> #123: bug in InputAsBytes fixed

- src/main/java/org/cactoos/func/IoCheckedFunc.java
- src/main/java/org/cactoos/func/UncheckedFunc.java
- src/main/java/org/cactoos/func/UncheckedProc.java
- src/main/java/org/cactoos/io/UncheckedBytes.java
- src/main/java/org/cactoos/text/UncheckedText.java
- src/test/java/org/cactoos/func/UncheckedFuncTest.java
- src/test/java/org/cactoos/func/UncheckedProcTest.java
- src/test/java/org/cactoos/func/UncheckedScalarTest.java
as per #126: fallbacks for `UncheckedBytes` and `UncheckedText`
> #126: fallbacks for UncheckedBytes and UncheckedText

- src/main/java/org/cactoos/io/BytesAsInput.java
- src/main/java/org/cactoos/io/TeeInput.java
- src/test/java/org/cactoos/io/TeeInputTest.java
> #128: more ctors

- src/main/java/org/cactoos/io/ResourceAsInput.java
- src/test/java/org/cactoos/io/ResourceAsInputTest.java
- src/test/resources/org/cactoos/large-text.txt
> #130: reproduced

- src/main/java/org/cactoos/io/UrlAsInput.java
- src/test/java/org/cactoos/io/UrlAsInputTest.java
as per #134: UrlAsInput accepts URI and String
> #134: UrlAsInput accepts URI and String

- src/main/java/org/cactoos/io/InputAsLSInput.java
as per #139: more args for `InputAsLSInput`
> #139: more args

- src/main/java/org/cactoos/Bytes.java
- src/main/java/org/cactoos/Input.java
- src/main/java/org/cactoos/Output.java
- src/main/java/org/cactoos/Proc.java
- src/main/java/org/cactoos/Text.java
- src/main/java/org/cactoos/func/FuncAsProc.java
- src/main/java/org/cactoos/func/FuncWithFallback.java
- src/main/java/org/cactoos/func/RunnableWithFallback.java
- src/test/java/org/cactoos/func/FuncWithFallbackTest.java
- src/test/java/org/cactoos/func/RunnableWithFallbackTest.java
as in #141: `RunnableWithFallback` added
> #141: RunnableWitFallback

- src/main/java/org/cactoos/func/RepeatedFunc.java
- src/main/java/org/cactoos/func/StickyFunc.java
- src/main/java/org/cactoos/func/StickyScalar.java
- src/main/java/org/cactoos/io/LengthOfInput.java
- src/main/java/org/cactoos/io/StderrOutput.java
- src/main/java/org/cactoos/io/StdinInput.java
- src/main/java/org/cactoos/io/StdoutOutput.java
- src/main/java/org/cactoos/io/StickyInput.java
- src/test/java/org/cactoos/func/RepeatedFuncTest.java
- src/test/java/org/cactoos/io/LengthOfInputTest.java
- src/test/java/org/cactoos/io/StickyInputTest.java
as in #146: `StickyInput` added
> #146: StickyInput

- src/main/java/org/cactoos/list/SortedIterable.java
- src/main/java/org/cactoos/list/SortedIterator.java
- src/test/java/org/cactoos/list/SortedIterableTest.java
as in #158: `SortedIterable` introduced
> #158: SortedIterable and SortedIterator

- src/main/java/org/cactoos/list/ItemOfIterable.java
- src/main/java/org/cactoos/list/ItemOfIterator.java
- src/test/java/org/cactoos/list/ItemOfIterableTest.java
- src/test/java/org/cactoos/list/ItemOfIteratorTest.java
> Modify FirstOf to ItemOfIterable

- src/main/java/org/cactoos/list/NaturalNumbers.java
- src/test/java/org/cactoos/list/NaturalNumbersTest.java
Step one towards funcAsIterator #101
> NaturalNumbers as Iterable

- src/main/java/org/cactoos/list/AllOf.java
- src/main/java/org/cactoos/list/ConcatenatedIterable.java
- src/main/java/org/cactoos/list/ConcatenatedIterator.java
- src/main/java/org/cactoos/list/IterableAsBoolean.java
- src/main/java/org/cactoos/list/IterableAsBooleans.java
- src/main/java/org/cactoos/list/IterableAsList.java
- src/main/java/org/cactoos/text/FormattedText.java
- src/test/java/org/cactoos/list/IterableAsListTest.java
Fix for #62
- add new ctor into IterableAsList
- reuse the new ctor instead of Arrays.asList in other ctors
> New ctor for iterable as list

- src/test/java/org/cactoos/io/LengthOfInputTest.java
- src/test/java/org/cactoos/io/StickyInputTest.java
- src/test/java/org/cactoos/io/UrlAsInputTest.java
> change external test resource to file system file

- src/main/java/org/cactoos/list/ConcatIterable.java
- src/main/java/org/cactoos/list/ConcatIterator.java
- src/main/java/org/cactoos/list/IterableAsBooleans.java
- src/main/java/org/cactoos/list/MapAsProperties.java
- src/main/java/org/cactoos/list/MappedIterable.java
- src/main/java/org/cactoos/list/MappedIterator.java
- src/test/java/org/cactoos/list/AllOfTest.java
- src/test/java/org/cactoos/list/AnyOfTest.java
- src/test/java/org/cactoos/list/ConcatIterableTest.java
- src/test/java/org/cactoos/list/MapAsPropertiesTest.java
- src/test/java/org/cactoos/list/MappedIterableTest.java
per #176: `MapAsProperties` introduced
> #176: MapAsProperties

- src/main/java/org/cactoos/func/Ternary.java
- src/test/java/org/cactoos/func/TernaryTest.java
As per #43 
`Ternary` introduce
> #43 Ternary

- src/test/java/org/cactoos/func/RetryFunc.java
- src/test/java/org/cactoos/func/RetryFuncTest.java
> #183: RetryFunc

- src/main/java/org/cactoos/list/SkippedIterable.java
- src/main/java/org/cactoos/list/SkippedIterator.java
- src/test/java/org/cactoos/list/SkippedIterableTest.java
- src/test/java/org/cactoos/list/SkippedIteratorTest.java
> Introduced SkippedIterable and SkippedIterator

- src/main/java/org/cactoos/list/IterableAsList.java
- src/main/java/org/cactoos/list/IterableAsMap.java
- src/main/java/org/cactoos/list/MapAsProperties.java
- src/main/java/org/cactoos/list/RepeatIterable.java
- src/main/java/org/cactoos/list/RepeatIterator.java
- src/main/java/org/cactoos/list/StickyIterable.java
- src/main/java/org/cactoos/list/StickyList.java
- src/main/java/org/cactoos/list/StickyMap.java
- src/test/java/org/cactoos/list/IterableAsListTest.java
- src/test/java/org/cactoos/list/IterableAsMapTest.java
- src/test/java/org/cactoos/list/MapAsPropertiesTest.java
- src/test/java/org/cactoos/list/StickyListTest.java
- src/test/java/org/cactoos/list/StickyMapTest.java
per #180:
* `StickyMap` added
* `StickyList` added
* decorators are not sticky any more
> #180: StickyMap and StickyList

- src/main/java/org/cactoos/func/Or.java
- src/test/java/org/cactoos/func/OrTest.java
> #144 Logical disjunction

- src/main/java/org/cactoos/text/RepeatedText.java
- src/test/java/org/cactoos/text/RepeatedTextTest.java
As per #203 :
`RepeatedText` introduced.
> #201: RepeatedText

- src/main/java/org/cactoos/text/JoinedText.java
- src/test/java/org/cactoos/text/JoinedTextTest.java
As per #205 :
`JoinedText` introduced.
> #205: JoinedText

- src/main/java/org/cactoos/text/NormalizedText.java
- src/test/java/org/cactoos/text/NormalizedTextTest.java
As per #201 :
`NormalizedText` introduced.
> #201: NormalizedText

- README.md
> #226: Fix some typos in README

- src/main/java/org/cactoos/Text.java
- src/main/java/org/cactoos/text/BytesAsText.java
- src/main/java/org/cactoos/text/FormattedText.java
- src/main/java/org/cactoos/text/JoinedText.java
- src/main/java/org/cactoos/text/LowerText.java
- src/main/java/org/cactoos/text/NormalizedText.java
- src/main/java/org/cactoos/text/NotNullText.java
- src/main/java/org/cactoos/text/RepeatedText.java
- src/main/java/org/cactoos/text/ReplacedText.java
- src/main/java/org/cactoos/text/ReversedText.java
- src/main/java/org/cactoos/text/StringAsText.java
- src/main/java/org/cactoos/text/TrimmedText.java
- src/main/java/org/cactoos/text/UncheckedText.java
- src/main/java/org/cactoos/text/UpperText.java
- src/test/java/org/cactoos/text/UncheckedTextTest.java
As per #56 let´s do `Text` extends `Comparable<Text>`.
> #56: Text extends Comparable<Text>

- README.md
> #233: Update README caused by change API

- src/main/java/org/cactoos/text/Base64DecodedText.java
- src/test/java/org/cactoos/func/RetryScalarTest.java
- src/test/java/org/cactoos/text/Base64DecodedTextTest.java
> #224 : Base64Decoded Text

- src/main/java/org/cactoos/text/SplitText.java
- src/test/java/org/cactoos/text/SplitTextTest.java
> #193 Added SplitText class 

- src/main/java/org/cactoos/BiFunc.java
- src/main/java/org/cactoos/list/ReducedIterable.java
- src/test/java/org/cactoos/list/ReducedIterableTest.java
see #240: `ReducedIterable` and `BiFunc` introduced
> #240: ReducedIterable and BiFunc

- src/main/java/org/cactoos/list/MapAsProperties.java
- src/main/java/org/cactoos/list/MapEntry.java
- src/test/java/org/cactoos/list/IterableAsMapTest.java
- src/test/java/org/cactoos/list/MapAsPropertiesTest.java
- src/test/java/org/cactoos/list/MapEntryTest.java
- src/test/java/org/cactoos/list/StickyMapTest.java
As per #190 
`MapEntry` introduced.
> #190: MapEntry

- src/main/java/org/cactoos/func/Equals.java
- src/test/java/org/cactoos/func/EqualsTest.java
As per #245.
`Equals` introduced.
> #245: Equals

- pom.xml
> #250: Let's Jacoco enforces minimum code coverage

- src/main/java/org/cactoos/io/InputWithFallback.java
- src/main/java/org/cactoos/text/SplitText.java
- src/test/java/org/cactoos/io/InputWithFallbackTest.java
- src/test/java/org/cactoos/text/SplitTextTest.java
#255: `InputWithFallback` added
> #255: InputWithFallback

- src/test/java/org/cactoos/func/AndTest.java
> #207: Eclipse cannot infer type arguments

- src/main/java/org/cactoos/Func.java
- src/main/java/org/cactoos/Input.java
- src/main/java/org/cactoos/Output.java
- src/test/java/org/cactoos/FuncTest.java
- src/test/java/org/cactoos/InputTest.java
- src/test/java/org/cactoos/OutputTest.java
- src/test/java/org/cactoos/package-info.java
As per #209 .
`NotNullInput` moved to `Input`.
`NotNullOutput` moved to `Output`.
`Func.NoNulls` introduced.
> #209: Input.NoNull, Ouput.NoNull and Func.NoNull

- src/main/java/org/cactoos/func/AsyncFunc.java
- src/test/java/org/cactoos/func/AsyncFuncTest.java
> #265: AsyncFunc

- src/main/java/org/cactoos/list/Max.java
- src/main/java/org/cactoos/list/Min.java
- src/test/java/org/cactoos/list/MaxTest.java
- src/test/java/org/cactoos/list/MinTest.java
> #269: Change Max and Min to a proper exception

- src/test/java/org/cactoos/text/LowerTextTest.java
As per #276.
- `LowerTextTest` introduced.
> #276: Test for LowerText

- src/test/java/org/cactoos/list/EndlessIterableTest.java
> #283 Test for EndlessIterable

- src/main/java/org/cactoos/func/Not.java
- src/test/java/org/cactoos/func/NotTest.java
As per #285.
- Rename `Neg` to `Not`.
> #285 Rename Neg to Not

- src/main/java/org/cactoos/list/NaturalNumbers.java
- src/test/java/org/cactoos/list/NaturalNumbersTest.java
> #287 Range for NaturalNumbers

- src/main/java/org/cactoos/list/IterableAsMap.java
- src/main/java/org/cactoos/list/StickyMap.java
> #302: new ctors

- src/main/java/org/cactoos/Proc.java
- src/test/java/org/cactoos/ProcTest.java
As per #298.
- `Proc.NoNulls` introduced.
> #298: NoNulls for Proc

- src/main/java/org/cactoos/Scalar.java
- src/test/java/org/cactoos/ScalarTest.java
As per #292 .
- `Scalar.NoNulls<T>` introduced.
> #292: NoNulls for Scalar<T>

- src/main/java/org/cactoos/Bytes.java
- src/test/java/org/cactoos/BytesTest.java
As per #294 .
- `Bytes.NoNulls` introduced.
> #294: NoNulls for Bytes

- src/main/java/org/cactoos/BiFunc.java
- src/test/java/org/cactoos/BiFuncTest.java
As per #296 .
- `BiFunc.NoNulls` introduced.
> #296: NoNulls for BiFunc

- src/main/java/org/cactoos/InputHasContent.java
> #304: InputHasContent

- src/main/java/org/cactoos/text/SubText.java
- src/test/java/org/cactoos/text/SubTextTest.java
As per #194:
`SubText` introduced.
> #194: SubText

- src/main/java/org/cactoos/func/CallableWithFallback.java
- src/test/java/org/cactoos/func/CallableWithFallbackTest.java
> #143 CallableWithFallback

- src/main/java/org/cactoos/text/LengthOfText.java
- src/test/java/org/cactoos/text/LengthOfTextTest.java
As per #289 
`LengthOfText` introduced
> #289 Length of text

- src/main/java/org/cactoos/io/InputAsBytes.java
- src/main/java/org/cactoos/io/LengthOfInput.java
- src/test/java/org/cactoos/io/InputAsBytesTest.java
- src/test/java/org/cactoos/io/InputAsLSInputTest.java
- src/test/java/org/cactoos/io/SlowInputStream.java
> #318: InputAsBytes fixed and tested

- src/main/java/org/cactoos/func/CallableOf.java
- src/main/java/org/cactoos/func/FuncOf.java
- src/main/java/org/cactoos/func/MatcherOf.java
- src/main/java/org/cactoos/func/ProcOf.java
- src/main/java/org/cactoos/func/RunnableOf.java
- src/test/java/org/cactoos/func/AndTest.java
- src/test/java/org/cactoos/func/AsyncFuncTest.java
- src/test/java/org/cactoos/func/RunnableOfTest.java
- src/test/java/org/cactoos/io/InputAsBytesTest.java
- src/test/java/org/cactoos/io/InputAsPropertiesTest.java
- src/test/java/org/cactoos/io/StickyInputTest.java
- src/test/java/org/cactoos/io/TeeInputTest.java
- src/test/java/org/cactoos/list/MapAsPropertiesTest.java
> #274: MatcherOf

- src/main/java/org/cactoos/func/FuncOf.java
- src/main/java/org/cactoos/func/FuncWithFallback.java
- src/main/java/org/cactoos/func/ProcOf.java
- src/test/java/org/cactoos/func/FuncWithFallbackTest.java
> #274: more ctors

- src/main/java/org/cactoos/io/ReaderAsInput.java
- src/test/java/org/cactoos/io/ReaderAsInputTest.java
> #333: ReaderAsInput

- src/main/java/org/cactoos/io/InputAsLSInput.java
Use same encoding for character-stream as declared in `getEncoding`
> UTF-8 encoding for InputAsLSInput

- README.md
- src/main/java/org/cactoos/text/TrimmedLeftText.java
- src/main/java/org/cactoos/text/TrimmedRightText.java
- src/test/java/org/cactoos/text/TrimmedLeftTextTest.java
- src/test/java/org/cactoos/text/TrimmedRightTextTest.java
Implementing right and left trim
> #358 : Right and Left Trim Implementation

- README.md
- src/main/java/org/cactoos/text/RotatedText.java
- src/test/java/org/cactoos/text/RotatedTextTest.java
> #362 : Rotated Text Implementation

- src/main/java/org/cactoos/scalar/BoolOf.java
- src/main/java/org/cactoos/scalar/DoubleOf.java
- src/main/java/org/cactoos/scalar/Equals.java
- src/main/java/org/cactoos/scalar/FloatOf.java
- src/main/java/org/cactoos/scalar/IntOf.java
- src/main/java/org/cactoos/scalar/IoCheckedScalar.java
- src/main/java/org/cactoos/scalar/LongOf.java
- src/main/java/org/cactoos/scalar/Max.java
- src/main/java/org/cactoos/scalar/Min.java
- src/main/java/org/cactoos/scalar/Not.java
- src/main/java/org/cactoos/scalar/Or.java
- src/main/java/org/cactoos/scalar/RetryScalar.java
- src/main/java/org/cactoos/scalar/StickyScalar.java
- src/main/java/org/cactoos/scalar/SyncScalar.java
- src/main/java/org/cactoos/scalar/UncheckedScalar.java
> #372 : Polish Scalar Package

- src/main/java/org/cactoos/iterator/Cycled.java
- src/main/java/org/cactoos/iterator/Endless.java
- src/main/java/org/cactoos/iterator/LengthOf.java
- src/main/java/org/cactoos/iterator/Limited.java
- src/main/java/org/cactoos/iterator/Mapped.java
- src/main/java/org/cactoos/iterator/Repeated.java
- src/main/java/org/cactoos/iterator/Skipped.java
- src/main/java/org/cactoos/iterator/Sorted.java
- src/main/java/org/cactoos/iterator/Sticky.java
> #388 : Polish Iterator Package

- src/main/java/org/cactoos/io/ReaderOf.java
- src/main/java/org/cactoos/io/TeeReader.java
- src/test/java/org/cactoos/io/TeeReaderTest.java
> #397 : Implementing TeeReader

- src/main/java/org/cactoos/func/IoCheckedBiFunc.java
- src/main/java/org/cactoos/func/UncheckedBiFunc.java
- src/test/java/org/cactoos/func/IoCheckedBiFuncTest.java
- src/test/java/org/cactoos/func/UncheckedBiFuncTest.java
Implementing Unchecked IoChecked Bifunc
> #399 : Implementing Unchecked IoChecked Bifunc 

- src/main/java/org/cactoos/func/StickyBiFunc.java
- src/test/java/org/cactoos/func/StickyBiFuncTest.java
> #400 : Implementing StickBiFunc

- src/main/java/org/cactoos/collection/StickyCollection.java
- src/test/java/org/cactoos/collection/StickyCollectionTest.java
> Added org.cactoos.collection.StickyCollection

- src/main/java/org/cactoos/collection/Filtered.java
- src/test/java/org/cactoos/collection/FilteredTest.java
As per #420 
`org.cactoos.collection.Filtered` introduced
> 420 collection.Filtered

- src/main/java/org/cactoos/collection/Limited.java
- src/test/java/org/cactoos/collection/LimitedTest.java
As per #418 
`org.cactoos.collection.Limited` introduced
> #418 collection.Limited

- src/main/java/org/cactoos/collection/Reversed.java
- src/test/java/org/cactoos/collection/ReversedTest.java
As per #417 
`org.cactoos.collection.Reversed` introduced
> #417 Reversed

- src/main/java/org/cactoos/collection/Joined.java
- src/test/java/org/cactoos/collection/JoinedTest.java
> Added org.cactoos.collection.Joined

- src/main/java/org/cactoos/iterable/Shuffled.java
- src/main/java/org/cactoos/iterator/Shuffled.java
- src/test/java/org/cactoos/iterable/ShuffledTest.java
- src/test/java/org/cactoos/iterator/ShuffledTest.java
Use cactoos in own project (simple game) Here is my use case:
```java
new Cycled<>(
new Shuffled<>(
new ListOf<>(
new Color(255, 150, 0),
new Color(100, 200, 100),
new Color(250, 50, 50)
)
)
)
```
I need randomly output any color on request.
> Prototype Shuffled iterator

- src/main/java/org/cactoos/scalar/Or.java
- src/test/java/org/cactoos/scalar/OrTest.java
> #439 Or More ctors

- src/main/java/org/cactoos/collection/Reversed.java
- src/test/java/org/cactoos/collection/ReversedTest.java
As per #417 
- Object[] toArray()
- toArray(final T[] array)
- containsAll(final Collection<?> list)
> #417 Reversed methods

- src/main/java/org/cactoos/text/SplitText.java
- src/test/java/org/cactoos/text/SplitTextTest.java
> #445 SplitText mistakes

- src/main/java/org/cactoos/iterable/IterableOf.java
- src/main/java/org/cactoos/list/Joined.java
- src/test/java/org/cactoos/list/JoinedTest.java
As per #447:
`org.cactoos.list.Joined` introduced
> #447 org.cactoos.list.Joined

- src/main/java/org/cactoos/Proc.java
- src/test/java/org/cactoos/ProcTest.java
1. I fixed the issue. 
2. I changed the unit test. So, now the number of method calls is controlled.
> #455 fixed the issue

- src/main/java/org/cactoos/time/DateAsText.java
- src/main/java/org/cactoos/time/DateOf.java
- src/main/java/org/cactoos/time/LocalDateTimeOf.java
- src/main/java/org/cactoos/time/OffsetDateTimeOf.java
- src/main/java/org/cactoos/time/ZonedDateTimeOf.java
- src/main/java/org/cactoos/time/package-info.java
- src/test/java/org/cactoos/time/DateAsTextTest.java
- src/test/java/org/cactoos/time/DateOfTest.java
- src/test/java/org/cactoos/time/LocalDateTimeOfTest.java
- src/test/java/org/cactoos/time/OffsetDateTimeOfTest.java
- src/test/java/org/cactoos/time/ZonedDateTimeOfTest.java
- src/test/java/org/cactoos/time/package-info.java
> #444 Printing and parsing of dates and times

- src/test/java/org/cactoos/collection/FilteredTest.java
> #500 Eclipse cannot infer type arguments in FilteredTest

- src/main/java/org/cactoos/text/HexOf.java
- src/test/java/org/cactoos/text/HexOfTest.java
> #510 HexOf

- src/main/java/org/cactoos/text/TextOf.java
- src/test/java/org/cactoos/text/FormattedTextTest.java
> #352 : Declarative Formatted Text

- src/main/java/org/cactoos/text/TextOf.java
- src/test/java/org/cactoos/text/TextOfTest.java
Implemented TextOf InputStream ctor https://github.com/yegor256/cactoos/issues/533
> Implemented TextOf InputStream ctor #533

- src/main/java/org/cactoos/collection/CollectionEnvelope.java
- src/main/java/org/cactoos/iterable/IterableEnvelope.java
- src/main/java/org/cactoos/list/ListEnvelope.java
- src/main/java/org/cactoos/map/MapEnvelope.java
- src/main/java/org/cactoos/scalar/NumberEnvelope.java
> #525 Make all Envelope classes abstract

- src/main/java/org/cactoos/iterable/Partitioned.java
- src/main/java/org/cactoos/iterator/Partitioned.java
- src/test/java/org/cactoos/iterable/PartitionedTest.java
- src/test/java/org/cactoos/iterator/PartitionedTest.java
> #531 Partitioned implementation

- src/main/java/org/cactoos/text/ReplacedText.java
- src/test/java/org/cactoos/text/ReplacedTextTest.java
> (NEW) ReplacedText has now been empowered with regex replacements

- src/main/java/org/cactoos/io/ResourceOf.java
- src/test/java/org/cactoos/io/ResourceOfTest.java
- src/test/resources/org/cactoos/small-text.txt
> Add constructors using Texts to ResourceOf

- pom.xml
- src/main/java/org/cactoos/io/LoggingInput.java
- src/main/java/org/cactoos/io/LoggingInputStream.java
- src/main/java/org/cactoos/io/LoggingOutput.java
- src/main/java/org/cactoos/io/LoggingOutputStream.java
- src/test/java/org/cactoos/io/FakeLogger.java
- src/test/java/org/cactoos/io/LoggingInputTest.java
- src/test/java/org/cactoos/io/LoggingOutputTest.java
As per #262:
- `FakeLogger` introduced. This a logger for tests
- `LoggingInput` introduced.
- `LoggingOutput` introduced.
> #262: LoggingInput and LoggingOutput

- README.md
> #524 Inheritance implementation only for decorating

- src/main/java/org/cactoos/io/TempFile.java
- src/test/java/org/cactoos/io/TempFileTest.java
(NEW) TempFile: a temporary file implemented as a Scalar<Path>
as per #63
> #63 Let's do a not procedural temporary file creation/deletion

- src/main/java/org/cactoos/time/DateAsText.java
- src/main/java/org/cactoos/time/LocalDateAsText.java
- src/main/java/org/cactoos/time/LocalDateTimeAsText.java
- src/main/java/org/cactoos/time/OffsetDateTimeAsText.java
- src/main/java/org/cactoos/time/ZonedDateTimeAsText.java
- src/test/java/org/cactoos/time/DateAsTextTest.java
- src/test/java/org/cactoos/time/LocalDateAsTextTest.java
- src/test/java/org/cactoos/time/LocalDateTimeAsTextTest.java
- src/test/java/org/cactoos/time/OffsetDateTimeAsTextTest.java
- src/test/java/org/cactoos/time/ZonedDateTimeAsTextTest.java
... not being able to be used with DateAsText. Splitted DateAsText into different impl. for the different Date classes.
> #560 fixing bug of LocalDateTime and LocalDate

- src/main/java/org/cactoos/text/IsBlank.java
> #573 improvement IsBlank

- src/main/java/org/cactoos/bytes/Base64Bytes.java
- src/main/java/org/cactoos/bytes/BytesBase64.java
- src/test/java/org/cactoos/bytes/Base64BytesTest.java
- src/test/java/org/cactoos/bytes/BytesBase64Test.java
Added Encoder/Decoder parameter to ctors.
> #555 made Base64 classes parameterized with Base64.Encoder/.Decoder

- src/main/java/org/cactoos/scalar/And.java
- src/main/java/org/cactoos/scalar/AndWithIndex.java
- src/main/java/org/cactoos/scalar/Folded.java
- src/main/java/org/cactoos/scalar/NumberOf.java
- src/main/java/org/cactoos/scalar/RetryScalar.java
- src/main/java/org/cactoos/scalar/StickyScalar.java
- src/main/java/org/cactoos/scalar/SyncScalar.java
- src/main/java/org/cactoos/scalar/Ternary.java
- src/test/java/org/cactoos/iterable/PropertiesOfTest.java
Samples for 
- AndWithIndex
- Folded
- Max, Min, SumOf, NumberOf
- RetryScalar
- StickyScalar, SyncScalar
- Ternary
> #461 we need more Javadoc examples

- src/test/java/org/cactoos/io/LengthOfTest.java
- src/test/java/org/cactoos/iterable/LengthOfTest.java
- src/test/java/org/cactoos/iterator/LengthOfTest.java
Implemented tests for `length of` class for #547 issue
> #547 Implemented tests for length of class

- src/main/java/org/cactoos/collection/Skipped.java
- src/test/java/org/cactoos/collection/SkippedTest.java
> #416 add collection.Skipped

- src/main/java/org/cactoos/collection/Mapped.java
- src/main/java/org/cactoos/iterable/Mapped.java
- src/main/java/org/cactoos/list/Mapped.java
- src/test/java/org/cactoos/collection/MappedTest.java
- src/test/java/org/cactoos/iterable/MappedTest.java
- src/test/java/org/cactoos/list/MappedTest.java
> #413 add normal Mapped.toString()

- src/main/java/org/cactoos/io/WriterAsOutputStream.java
- src/test/java/org/cactoos/io/WriterAsOutputStreamTest.java
> (#561) override close() method of WriterAsOutputStream

- src/main/java/org/cactoos/scalar/SumOf.java
- src/test/java/org/cactoos/scalar/SumOfTest.java
Using BigDecimal for summation of values. Similar to `AvgOf` processing.
> #600 fixing overflow error with int value

- src/main/java/org/cactoos/io/GzipInput.java
- src/main/java/org/cactoos/io/GzipOutput.java
- src/test/java/org/cactoos/io/GzipInputTest.java
- src/test/java/org/cactoos/io/GzipOutputTest.java
#502 is mine now as per https://github.com/yegor256/cactoos/issues/502#issuecomment-360621144 and #503 seems to be dead at this point.
Based on #503. Fixed the remaining remarks: formating + more tests.
Close #502, close #503
> #502 GzipInput and GzipOutput

- src/main/java/org/cactoos/iterable/Reversed.java
#608 Removed code duplication of `iterable/Reversed` and `collection/Reversed`
> #608 Removed code duplication of Reversed

- src/main/java/org/cactoos/io/Directory.java
- src/test/java/org/cactoos/io/DirectoryTest.java
> #599 fix javadocs and test name

- src/main/java/org/cactoos/scalar/SumOfDoubleScalar.java
- src/main/java/org/cactoos/scalar/SumOfFloatScalar.java
- src/main/java/org/cactoos/scalar/SumOfIntScalar.java
- src/main/java/org/cactoos/scalar/SumOfLongScalar.java
- src/main/java/org/cactoos/scalar/SumOfScalar.java
- src/test/java/org/cactoos/scalar/SumOfDoubleScalarTest.java
- src/test/java/org/cactoos/scalar/SumOfFloatScalarTest.java
- src/test/java/org/cactoos/scalar/SumOfIntScalarTest.java
- src/test/java/org/cactoos/scalar/SumOfLongScalarTest.java
- src/test/java/org/cactoos/scalar/SumOfScalarTest.java
#619 Implemented SumOfScalar to sum up values from its scalars
> #619 Implemented SumOfScalar to sum up values from its scalars

- src/main/java/org/cactoos/map/MapEnvelope.java
- src/test/java/org/cactoos/map/MapOfTest.java
> #646 - MapOf and MapEnvelope do not have pretty toString method

- src/main/java/org/cactoos/list/ListEnvelope.java
- src/test/java/org/cactoos/list/ListOfTest.java
> #648 added equals, hashCode and toString methods to ListEnvelope

- src/test/java/org/cactoos/map/MapOfTest.java
As per #652.
I have written the missing tests for the constructors for the MapOf class. Now, all of the constructors are properly tested.
One of the tests was not included as it fails (see #659).
> #652 - Added tests for ctors for the MapOf class

- src/test/java/org/cactoos/scalar/AndInThreadsTest.java
As per #654.
I have written unit tests for all of the constructors that were not tested in the `AndInThreads` class.
> #654 - AndInThreads - covered all ctors with tests.

- src/test/java/org/cactoos/func/ProcOfTest.java
As per #667 
I have written all necessary tests for the ProcOf class.
> #667 - Added tests for ProcOf class.

- src/main/java/org/cactoos/io/LengthOf.java
- src/test/java/org/cactoos/io/LengthOfTest.java
Pull request for the issue #636
> #636: LengthOfTest.java:89-91: Fix calculation of length for

- src/test/java/org/cactoos/func/RetryFuncTest.java
For #670 
**Problem**
Three ctors of RetryFunc are not covered by unit tests
**Solution**
Added more tests.
> #670 Ctors of RetryFunc are not covered by unit tests

- src/main/java/org/cactoos/scalar/SumOf.java
fixing #699 by replacing sum calculating for-loop with usage of `Reduced` class.
> #699 replacing for loop with Reduced.

- src/test/java/org/cactoos/map/MapEnvelopeTest.java
The problem in #681:
Class `MapEnvelope` has low test coverage
The solution:
Add few unit tests to reach full coverage
> #681 add few unit tests to reach full coverage

- src/test/java/org/cactoos/func/SolidBiFuncTest.java
This pull request is for #672: it adds new test cases for all ctors of SolidBiFunc.
> #672: Add test cases for all ctors of SolidBiFunc

- src/main/java/org/cactoos/io/LoggingInputStream.java
- src/test/java/org/cactoos/io/FakeHandler.java
- src/test/java/org/cactoos/io/LoggingInputTest.java
Retrieve logger level from parent if it inherits
> #644 Using LoggingInput without providing a Logger does not work

- src/test/java/org/cactoos/io/InputStreamOfTest.java
Added more tests for `InputStreamOf`
> #661 InputStreamOf test class is incomplete

- src/test/java/org/cactoos/io/OutputToTest.java
Pull request for issue #686. It covers all ctors of the OutputTo class by tests.
> #686: Add more tests for OutputTo

- README.md
Added @driver733 to the list of contributors.
> Added @driver733 to the list of contributors.

- src/main/java/org/cactoos/func/TimedFunc.java
- src/test/java/org/cactoos/func/TimedFuncTest.java
`TimedFunc` introduced for #761
> #761 TimedFunc

- src/main/java/org/cactoos/iterable/IterableOf.java
> #773 Removed usage of Arrays.asList

- src/main/java/org/cactoos/io/Zip.java
- src/test/java/org/cactoos/io/ZipTest.java
For #638 
**Problem**
There aren't any OOP way to create ZIP archive from `Directory`.
**Solution**
Add `Zip implements Input` which wraps the `Directory` to `Input` as result of work with `ZipOutputStream`.
> #638 Zip a list of files (or a Directory)

- src/main/java/org/cactoos/iterator/Joined.java
- src/test/java/org/cactoos/iterator/JoinedTest.java
Fix problem with org.cactoos.iterable.Joined for #755
> #755 Fix problem with Joined

- src/main/java/org/cactoos/io/TailInput.java
- src/test/java/org/cactoos/io/TailInputTest.java
For #765.
Created `TailInput` class that provides last N bytes of given `Input`.
> #765 added TailInput

- README.md
- src/main/java/org/cactoos/iterable/IterableOfBooleans.java
- src/main/java/org/cactoos/iterable/IterableOfBytes.java
- src/main/java/org/cactoos/iterable/IterableOfChars.java
- src/main/java/org/cactoos/iterable/IterableOfDoubles.java
- src/main/java/org/cactoos/iterable/IterableOfFloats.java
- src/main/java/org/cactoos/iterable/IterableOfInts.java
- src/main/java/org/cactoos/iterable/IterableOfLongs.java
- src/main/java/org/cactoos/iterable/IterableOfShorts.java
- src/test/java/org/cactoos/iterable/IterableOfBooleansTest.java
- src/test/java/org/cactoos/iterable/IterableOfBytesTest.java
- src/test/java/org/cactoos/iterable/IterableOfCharsTest.java
- src/test/java/org/cactoos/iterable/IterableOfDoublesTest.java
- src/test/java/org/cactoos/iterable/IterableOfFloatsTest.java
- src/test/java/org/cactoos/iterable/IterableOfIntsTest.java
- src/test/java/org/cactoos/iterable/IterableOfLongsTest.java
- src/test/java/org/cactoos/iterable/IterableOfShortsTest.java
Introduced iterables for primitive types for #748
> #748 Iterables for primitive types

- src/main/java/org/cactoos/scalar/Equality.java
- src/test/java/org/cactoos/scalar/EqualityTest.java
Introduced `Equality` for #308
> #308 Equality

- src/main/java/org/cactoos/iterable/IterableOfBooleans.java
- src/main/java/org/cactoos/iterable/IterableOfBytes.java
- src/main/java/org/cactoos/iterable/IterableOfChars.java
- src/main/java/org/cactoos/iterator/IteratorOfBooleans.java
- src/main/java/org/cactoos/iterator/IteratorOfChars.java
- src/test/java/org/cactoos/iterator/IteratorOfBooleansTest.java
- src/test/java/org/cactoos/iterator/IteratorOfCharsTest.java
#803 
- added `IteratorOfBooleans` and `IteratorOfChars` and used them in appropriate IterablesOf
- added tests for those
- added todo to implement similar iterators for bytes and doubles
> #803 added iterator of booleans and chars

- src/main/java/org/cactoos/text/RandomText.java
- src/test/java/org/cactoos/text/RandomTextTest.java
Pull request for #790.
I've created a new class RandomText that generates a random text ("captain obvious" :D) allowing to specify length and characters of the resulting text. As well I've added a text for that class.
> #790: Create RandomText

- src/main/java/org/cactoos/func/CheckedBiFunc.java
- src/main/java/org/cactoos/func/CheckedBiProc.java
- src/main/java/org/cactoos/func/CheckedFunc.java
- src/main/java/org/cactoos/func/CheckedProc.java
- src/test/java/org/cactoos/func/CheckedBiFuncTest.java
- src/test/java/org/cactoos/func/CheckedBiProcTest.java
- src/test/java/org/cactoos/func/CheckedFuncTest.java
- src/test/java/org/cactoos/func/CheckedProcTest.java
Introduced `Checked*` classes for #799
> #799 rest of Checked* classes

- src/main/java/org/cactoos/iterable/Joined.java
- src/main/java/org/cactoos/list/Joined.java
- src/test/java/org/cactoos/iterable/JoinedTest.java
- src/test/java/org/cactoos/list/JoinedTest.java
> #806 Joined

- src/main/java/org/cactoos/scalar/CheckedScalar.java
> #799 removed puzzle

- src/main/java/org/cactoos/scalar/And.java
- src/main/java/org/cactoos/scalar/Or.java
- src/test/java/org/cactoos/scalar/AndTest.java
- src/test/java/org/cactoos/scalar/OrTest.java
Align And and Or ctors for #754
> #754 Align And and Or ctors

- src/main/java/org/cactoos/text/TextEnvelope.java
> #849 removed stale todo

- src/main/java/org/cactoos/func/AsyncFunc.java
- src/main/java/org/cactoos/func/FuncOf.java
- src/main/java/org/cactoos/func/IoCheckedProc.java
- src/main/java/org/cactoos/func/RepeatedFunc.java
- src/main/java/org/cactoos/func/RetryFunc.java
- src/main/java/org/cactoos/func/TimedFunc.java
- src/main/java/org/cactoos/func/UncheckedProc.java
- src/test/java/org/cactoos/func/FuncOfTest.java
- src/test/java/org/cactoos/func/RepeatedFuncTest.java
- src/test/java/org/cactoos/map/MapEnvelopeTest.java
Pull request for #861 
Remove bad constructor and create puzzles where the solution is not straightforward.
> #861 Remove FuncOf.ctr(Proc<X>)

- pom.xml
- src/main/java/org/cactoos/io/Zip.java
- src/main/java/org/cactoos/scalar/AndWithIndex.java
- src/main/java/org/cactoos/scalar/Constant.java
- src/main/java/org/cactoos/scalar/Reduced.java
- src/main/java/org/cactoos/scalar/RetryScalar.java
- src/main/java/org/cactoos/scalar/StickyScalar.java
- src/main/java/org/cactoos/scalar/SumOfDoubleScalar.java
- src/main/java/org/cactoos/scalar/SumOfFloatScalar.java
- src/main/java/org/cactoos/scalar/SumOfIntScalar.java
- src/main/java/org/cactoos/scalar/SumOfLongScalar.java
- src/main/java/org/cactoos/scalar/SyncScalar.java
- src/main/java/org/cactoos/scalar/Ternary.java
- src/main/java/org/cactoos/text/ComparableText.java
- src/main/java/org/cactoos/text/ReplacedText.java
Pull request for #818
* Add `mvn javadoc:javadoc` during "qulice" profile execution
* Fix several javadoc HTML errors
> #818 javadoc check

- src/main/java/org/cactoos/text/JoinedText.java
- src/main/java/org/cactoos/text/PaddedStartText.java
- src/main/java/org/cactoos/text/ReplacedText.java
- src/main/java/org/cactoos/text/ReversedText.java
- src/main/java/org/cactoos/text/RotatedText.java
- src/main/java/org/cactoos/text/SubText.java
- src/main/java/org/cactoos/text/SwappedCaseText.java
- src/main/java/org/cactoos/text/TextBase64.java
Refactored some `Text` classes to use `TextEnvelope` for #878 
I had to suppres pqulice warnings in three classes. I don't know why qulice is complaining, must probably a bug.
> #878 more Text classes refactored to use TextEnvelope

- src/test/java/org/cactoos/bytes/HexBytesTest.java
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:
- You made a small amount of changes (less than 100 lines, less than 10 files)
- You made changes related to only one bug (create separate PRs for separate problems)
- You are ready to defend your changes (there will be a code review)
- You don't touch what you don't understand
- You ran the build locally and it passed
This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html
Thank you for your contribution!
> Corrected typo in the HexBytesTest empty text

- src/main/java/org/cactoos/time/DateAsText.java
- src/main/java/org/cactoos/time/DateOf.java
- src/main/java/org/cactoos/time/Iso.java
- src/main/java/org/cactoos/time/LocalDateAsText.java
- src/main/java/org/cactoos/time/LocalDateTimeAsText.java
- src/main/java/org/cactoos/time/LocalDateTimeOf.java
- src/main/java/org/cactoos/time/OffsetDateTimeAsText.java
- src/main/java/org/cactoos/time/OffsetDateTimeOf.java
- src/main/java/org/cactoos/time/ZonedDateTimeAsText.java
- src/main/java/org/cactoos/time/ZonedDateTimeOf.java
Implement Scalar in Iso class for #872
> #872 Iso class implement Scalar

- src/test/java/org/cactoos/collection/CollectionOfTest.java
I replaced iterator with iterable for #902 as it is discussed in #911
> #902 Fix iterator test of CollectionOfTest

- src/main/java/org/cactoos/text/AbbreviatedText.java
- src/main/java/org/cactoos/text/Base64Text.java
Refactored Base64Text as described in #929.
> Refactoring Base64Text (#929)

- src/main/java/org/cactoos/scalar/DivisionOf.java
- src/main/java/org/cactoos/scalar/MultiplicationOf.java
- src/test/java/org/cactoos/scalar/DivisionOfTest.java
- src/test/java/org/cactoos/scalar/MultiplicationOfTest.java
MultiplicationOf and DivisionOf for supporting more math operations as described in #864 .
> Implement a new scalar: MultiplicationOf (#864)

- pom.xml
- src/main/java/org/cactoos/text/Strict.java
- src/test/java/org/cactoos/text/StrictTest.java
Strict that implements Text as described in #941.  It encapsulates Text and validates it using predicate which is Func<String, Boolean>.
> #941 Strict with tests for validating Text

- src/main/java/org/cactoos/collection/NoNulls.java
- src/main/java/org/cactoos/iterable/NoNulls.java
- src/main/java/org/cactoos/iterator/NoNulls.java
- src/main/java/org/cactoos/list/NoNulls.java
- src/main/java/org/cactoos/map/NoNulls.java
- src/test/java/org/cactoos/collection/NoNullsTest.java
- src/test/java/org/cactoos/collection/ReversedTest.java
- src/test/java/org/cactoos/iterator/JoinedTest.java
- src/test/java/org/cactoos/iterator/NoNullsTest.java
As described in #1017.
- CollectionNoNulls is now NoNulls, the same holds true for test
- IteratorNoNulls is now NoNulls, the same holds true for test
> #1017 Making NoNulls API consistent

- .gitignore
- src/main/java/org/cactoos/scalar/HashCode.java
- src/test/java/org/cactoos/scalar/HashCodeTest.java
For #978 
* Added new `HashCode` scalar
> (#978) HashCode scalar

- src/main/java/org/cactoos/func/CallableOf.java
- src/main/java/org/cactoos/func/Repeated.java
- src/test/java/org/cactoos/func/RepeatedTest.java
Solving #888 puzzle. According to recommendations by ARC (#918 ([comment](https://github.com/yegor256/cactoos/pull/918#issuecomment-402320948))), I simply removed the constructor using null and taking a Proc.
> Removed null usage in Repeated ctor (#888)

- src/main/java/org/cactoos/text/ComparableText.java
- src/test/java/org/cactoos/text/ComparableTextTest.java
This PR:
- #1030 
- Adds unit tests for #1030
> (#1030) ComparableText is not equal to the same text

- src/main/java/org/cactoos/io/LoggingInputStream.java
- src/test/java/org/cactoos/io/LoggingInputStreamTest.java
Issue #1052
A cumulative rebase of the PR #1028
> (#1052) LoggingInputStream.read() of empty stream should return -1

- src/main/java/org/cactoos/scalar/Binary.java
- src/test/java/org/cactoos/scalar/BinaryTest.java
This PR is for #825 issue. It covers:
- new Binary class
- unit tests for Binary class
> (#825) Binary

- src/test/java/org/cactoos/map/MapEnvelopeTest.java
Comparison of MapEnvelope with derived classes already supported. I've added the test for that.
> (#893) Test for comparison of MapEnvelope and derived class

- README.md
- src/main/java/org/cactoos/text/Abbreviated.java
- src/main/java/org/cactoos/text/PaddedStart.java
- src/main/java/org/cactoos/text/Reversed.java
- src/main/java/org/cactoos/text/Rotated.java
- src/main/java/org/cactoos/text/Split.java
- src/main/java/org/cactoos/text/Sub.java
- src/main/java/org/cactoos/text/SwappedCase.java
- src/main/java/org/cactoos/text/TrimmedLeft.java
- src/main/java/org/cactoos/text/TrimmedRight.java
- src/main/java/org/cactoos/text/Upper.java
- src/test/java/org/cactoos/collection/MappedTest.java
- src/test/java/org/cactoos/iterable/MappedTest.java
- src/test/java/org/cactoos/list/MappedTest.java
- src/test/java/org/cactoos/map/SolidTest.java
- src/test/java/org/cactoos/text/ComparableTextTest.java
- src/test/java/org/cactoos/text/PaddedStartTest.java
- src/test/java/org/cactoos/text/ReversedTest.java
- src/test/java/org/cactoos/text/RotatedTest.java
- src/test/java/org/cactoos/text/SplitTest.java
- src/test/java/org/cactoos/text/SubTest.java
- src/test/java/org/cactoos/text/SwappedCaseTest.java
- src/test/java/org/cactoos/text/TrimmedLeftTest.java
- src/test/java/org/cactoos/text/TrimmedRightTest.java
- src/test/java/org/cactoos/text/UpperTest.java
Continued to refactor the class names as mentioned in #1074.
> (#1074) apply new naming convention in text package

- pom.xml
- src/test/java/org/cactoos/time/DateAsTextTest.java
- src/test/java/org/cactoos/time/DateOfTest.java
- src/test/java/org/cactoos/time/LocalDateTimeAsTextTest.java
- src/test/java/org/cactoos/time/LocalDateTimeOfTest.java
- src/test/java/org/cactoos/time/OffsetDateTimeAsTextTest.java
- src/test/java/org/cactoos/time/OffsetDateTimeOfTest.java
- src/test/java/org/cactoos/time/ZonedDateTimeAsTextTest.java
- src/test/java/org/cactoos/time/ZonedDateTimeOfTest.java
This is for #951,
I covered the time package and also used `Assertion`.
> (#951) Use 00 matchers and Assertion in time classes

- src/main/java/org/cactoos/text/package-info.java
I've forgotten to remove the puzzle. This is done now.
> (#1074) removed puzzle

- src/main/java/org/cactoos/func/Retry.java
- src/main/java/org/cactoos/scalar/Retry.java
- src/test/java/org/cactoos/func/RetryTest.java
- src/test/java/org/cactoos/scalar/RetryTest.java
PR for the issue #909 
- added [Duration](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html)
- added Thread.sleep to wait between executions
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:
> (#909) Add possibility to let Retry wait between attempts

- src/main/java/org/cactoos/func/FuncEnvelope.java
- src/main/java/org/cactoos/scalar/ScalarEnvelope.java
- src/test/java/org/cactoos/func/FuncEnvelopeTest.java
- src/test/java/org/cactoos/scalar/ScalarEnvelopeTest.java
For #826.
Nothing special here, I added some very basic tests too.
> (#826) Envelopes for Scalar and Func

- src/test/java/org/cactoos/func/RetryTest.java
This is for #1088 
I added test which verifies case when thread is interrupted while waiting.
> (#1088) Add test to check interruption in wait

- src/main/java/org/cactoos/collection/CollectionEnvelope.java
forgot to remove the `@todo` in #1130 that took care of #1109.
> (#1109) Make CollectionEnvelope.toString final and fix Mapped

- src/main/java/org/cactoos/io/package-info.java
- src/test/java/org/cactoos/io/BytesOfTest.java
- src/test/java/org/cactoos/io/CheckedBytesTest.java
- src/test/java/org/cactoos/io/CheckedInputTest.java
- src/test/java/org/cactoos/io/CheckedOutputTest.java
- src/test/java/org/cactoos/io/DeadInputTest.java
- src/test/java/org/cactoos/io/DeadOutputTest.java
This is for #1117. I've continued the work and introduced a new todo
> (#1117) Remove some more static method calls in test

- src/main/java/org/cactoos/scalar/MaxOf.java
- src/test/java/org/cactoos/scalar/MaxOfTest.java
For #1135 
- Fix `MaxOf` to work properly with negative numbers
- `MinOf` doesn't need fix.
> (#1133) MaxOf doesn't work with negative numbers

- .gitlint
(#1178) Update gitlint since date
- Updated gitlint since date so 937c047 does not fail build
> (#1178) Update gitlint since date

- src/main/java/org/cactoos/collection/Sliced.java
- src/main/java/org/cactoos/iterable/Sliced.java
- src/main/java/org/cactoos/iterator/HeadOf.java
- src/main/java/org/cactoos/iterator/Partitioned.java
- src/main/java/org/cactoos/iterator/Skipped.java
- src/main/java/org/cactoos/iterator/Sliced.java
- src/test/java/org/cactoos/collection/SlicedTest.java
- src/test/java/org/cactoos/iterable/SlicedTest.java
- src/test/java/org/cactoos/iterator/SlicedTest.java
#1188 
Decorator to get a portion(slice) of: 
-  Iterator
-  Iterable
-  Collection
by providing the initial index and a max number of elements to retrieve
> (#1188) Sliced Iterator, Iterable, Collection implementations 

- src/main/java/org/cactoos/iterator/Skipped.java
This is for https://github.com/yegor256/cactoos/issues/1192
> (#1192) Using `iterator.Sliced` inside the `iterator.Skipped`

- pom.xml
- src/test/java/org/cactoos/iterator/HeadOfTest.java
- src/test/java/org/cactoos/iterator/IteratorOfTest.java
- src/test/java/org/cactoos/iterator/JoinedTest.java
- src/test/java/org/cactoos/iterator/RepeatedTest.java
- src/test/java/org/cactoos/iterator/ShuffledTest.java
- src/test/java/org/cactoos/iterator/SkippedTest.java
- src/test/java/org/cactoos/iterator/SortedTest.java
- src/test/java/org/cactoos/iterator/TailOfTest.java
> (#1166) Remove some more non OO matchers

- src/main/java/org/cactoos/iterator/Partitioned.java
This is for https://github.com/yegor256/cactoos/issues/1191
> (#1191) Using `iterator.Sliced` inside the `iterator.Partitioned`

- src/test/java/org/cactoos/bytes/Base64BytesTest.java
- src/test/java/org/cactoos/bytes/BytesBase64Test.java
- src/test/java/org/cactoos/bytes/HexOfTest.java
- src/test/java/org/cactoos/func/BiFuncOfTest.java
- src/test/java/org/cactoos/func/ChainedTest.java
- src/test/java/org/cactoos/func/CheckedBiFuncTest.java
- src/test/java/org/cactoos/func/CheckedBiProcTest.java
- src/test/java/org/cactoos/func/CheckedFuncTest.java
- src/test/java/org/cactoos/func/CheckedProcTest.java
- src/test/java/org/cactoos/func/FuncOfTest.java
- src/test/java/org/cactoos/io/package-info.java
This is for https://github.com/yegor256/cactoos/issues/1228
> (#1228) Remove some more static call to assert

- src/main/java/org/cactoos/collection/Immutable.java
- src/main/java/org/cactoos/list/Immutable.java
- src/test/java/org/cactoos/list/ImmutableTest.java
- src/test/java/org/cactoos/list/ListEnvelopeTest.java
This is for https://github.com/yegor256/cactoos/issues/1224
> (#1224) Making `list/Immutable` truly immutable

- .gitlint
- 2019-12-05.md
Project report 2019-12-05 and commit lint removal.
> Project report 2019-12-05

- src/main/java/org/cactoos/text/StartsWith.java
- src/test/java/org/cactoos/text/StartsWithTest.java
This is for #1265
Created class StartsWith
Created tests on StartsWith class
> (#1265) StartsWith added for Text

- src/main/java/org/cactoos/iterator/TailOf.java
- src/test/java/org/cactoos/iterator/TailOfTest.java
This is for #1262, I had to improve the test because it wasn't catching ordering bugs.
> (#1262) TailOf is now based on Reversed

- src/main/java/org/cactoos/iterator/HeadOf.java
- src/test/java/org/cactoos/iterator/HeadOfTest.java
This is for issue #1194
Refactor of `HeadOf` using `Sliced `primitive.
> (#1194) HeadOf.java: refactored implementation to use Sliced

- src/main/java/org/cactoos/collection/NoNulls.java
- src/test/java/org/cactoos/collection/NoNullsTest.java
This is for issue: https://github.com/yegor256/cactoos/issues/1274
> (#1274) Make addAll properly call internal addAll

- src/main/java/org/cactoos/scalar/SumOfScalar.java
- src/main/java/org/cactoos/text/EndsWith.java
- src/test/java/org/cactoos/text/EndsWithTest.java
This PR is for issue [1266](https://github.com/yegor256/cactoos/issues/1266)
> (#1266) New scalar for text ending predicate

- src/main/java/org/cactoos/experimental/Timed.java
- src/main/java/org/cactoos/experimental/Timeout.java
- src/test/java/org/cactoos/experimental/TimedTest.java
- src/test/java/org/cactoos/experimental/TimeoutTest.java
This is for #1000 
* Created class `Timeout`
* Created tests on `Timeout` class
* Removed puzzle
> (#1000) Created Timeout class

- README.md
- src/verifier/verifications.xml
For #1281: Correction of year value in verifications.xml, changed architect name
> For #1281: corrections on master

- .rultor.yml
For #1285: Updating rultor image to yegor256/rultor-image
> For #1285: updating rultor image

- src/main/java/org/cactoos/text/Split.java
- src/test/java/org/cactoos/text/SplitTest.java
> (#1251) Add limit parameter to Split

- src/main/java/org/cactoos/scalar/FirstOf.java
- src/test/java/org/cactoos/scalar/FirstOfTest.java
This PR is for issue [1276](https://github.com/yegor256/cactoos/issues/1276)
> Fixed fallback function in the FirstOf class

- src/main/java/org/cactoos/io/TempFolder.java
- src/test/java/org/cactoos/io/TempFolderTest.java
This PR is for issue [1284](https://github.com/yegor256/cactoos/issues/1284)
> (#1284) Fixed TempFolder close method

- src/main/java/org/cactoos/list/Joined.java
- src/main/java/org/cactoos/list/package-info.java
- src/test/java/org/cactoos/list/JoinedTest.java
> (#1291) Joined list can be mutable

- README.md
This small PR is just to update the list of contributers with new people not currently listed there.
> (#0000) Contibuters readme update

- src/main/java/org/cactoos/text/Joined.java
- src/test/java/org/cactoos/text/JoinedTest.java
[#1258](https://github.com/yegor256/cactoos/issues/1258)
> #1258 added extra constructor

- .rultor.yml
For #1318: fixing rultor execution
> For #1318: fixing rultor execution

- src/test/java/org/cactoos/io/InputStreamOfTest.java
- src/test/java/org/cactoos/io/InputWithFallbackTest.java
- src/test/java/org/cactoos/io/LoggingInputTest.java
- src/test/java/org/cactoos/io/LoggingOutputTest.java
- src/test/java/org/cactoos/io/Md5DigestOfTest.java
- src/test/java/org/cactoos/io/ResourceOfTest.java
- src/test/java/org/cactoos/io/Sha1DigestOfTest.java
- src/test/java/org/cactoos/io/Sha256DigestOfTest.java
- src/test/java/org/cactoos/io/SlowInputTest.java
- src/test/java/org/cactoos/io/StickyTest.java
- src/test/java/org/cactoos/io/TailOfTest.java
- src/test/java/org/cactoos/io/TeeInputFromByteArrayTest.java
- src/test/java/org/cactoos/io/package-info.java
PR for #1235 
Replaced some `assertThat` method usages with `Assertion` in `io` package. Updated `todo`.
> #1235 - Added more Assertions to tests.

- src/test/java/org/cactoos/iterable/SkippedTest.java
PR for #1326 
Removed duplicate String literals.
> #1326 - Removed duplicate literals warning.

- src/test/java/org/cactoos/io/TeeInputFromBytesTest.java
- src/test/java/org/cactoos/io/TeeInputStreamTest.java
- src/test/java/org/cactoos/io/TeeOutputStreamTest.java
- src/test/java/org/cactoos/io/TeeOutputTest.java
- src/test/java/org/cactoos/io/TeeReaderTest.java
- src/test/java/org/cactoos/io/TempFileTest.java
- src/test/java/org/cactoos/io/UncheckedBytesTest.java
- src/test/java/org/cactoos/io/ZipTest.java
- src/test/java/org/cactoos/io/package-info.java
> #1331 - Replacing usage of MatcherAssert.assertThat

- src/test/java/org/cactoos/io/TeeInputFromFileTest.java
- src/test/java/org/cactoos/io/TeeInputFromInputTest.java
- src/test/java/org/cactoos/io/TeeInputFromPathTest.java
- src/test/java/org/cactoos/io/package-info.java
> #1340 - Replacing usage of MatcherAssert.assertThat with Assertion

- src/test/java/org/cactoos/scalar/FirstOfTest.java
This is a PR with forgotten unit-test for https://github.com/yegor256/cactoos/issues/1276
> (#1276) Forgotten unit-test

- .rultor.yml
For #1346: changed rultor image on rultor.yml
> For #1436: changed rultor image on rultor.yml

- .rultor.yml
For #1346: fixing java version
> For #1346: fixing java version

- pom.xml
For #1346: updating sonar cloud plugin version
> For #1346: updating sonar cloud plugin version

- .rultor.yml
For #1346: turning off sonar on rultor executions
> For #1346: turning off sonar on rultor executions

- .rultor.yml
For #1346: restoring sonar check on release
> For #1346: restoring sonar check on release

- .rultor.yml
For #1352: Fixing rultor release configurations
> For #1352: Fixing rultor release configurations

- pom.xml
For #1346: 
restoring to use sonar default properties read from `settings.xml`
> For 1346: restoring sonar default properties

- pom.xml
For #1346: same config as jpeek
> For #1346: same config as jpeek

- .gitignore
- src/test/java/org/cactoos/io/TeeInputFromBytesTest.java
> #1341: TeeInput - Correction of tests

- pom.xml
For #1346:  adding sonarcloud url
> For 1346: adding sonarcloud url

- src/main/java/org/cactoos/scalar/FirstOf.java
- src/test/java/org/cactoos/scalar/FirstOfTest.java
This pull-request has no corresponding issue.
* Added extra-ctor with default `condition` (always `true`) to FirstOf
> FirstOf: added extra-ctor

- src/test/java/org/cactoos/scalar/AndInThreadsTest.java
- src/test/java/org/cactoos/scalar/AndTest.java
- src/test/java/org/cactoos/scalar/AndWithIndexTest.java
- src/test/java/org/cactoos/scalar/AvgOfTest.java
- src/test/java/org/cactoos/scalar/package-info.java
#1362 
- Replaced MatcherAssert.assertThat functions to Assertion objects
> 1362 Work on replacing MatcherAssert to Assertion

- src/test/java/org/cactoos/io/TeeInputFromBytesTest.java
- src/test/java/org/cactoos/io/TeeInputFromCharArrayTest.java
- src/test/java/org/cactoos/io/TeeInputFromCharSequenceTest.java
#1360
- Correct tests of TeeInputs
> 1360 Correct TeeInput tests

- pom.xml
For #1346: added organization to sonar configuration
> For #1346: added organization to sonar configuration

- src/main/java/org/cactoos/text/Contains.java
- src/test/java/org/cactoos/text/ContainsTest.java
This pull-request has no corresponding issue.
* Added new class text.Contains (by analogy with text.EndsWith)
* Added unit-test for this new class
> new class text.Contains (by analogy with text.EndsWith)

- .rultor.yml
- pom.xml
For #1346: added cactoos profiles
> For #1346: added cactoos profiles

- .rultor.yml
> For #1346: added gpg config

- pom.xml
For #1346: added gpg config to pom.xml
> For #1346: added gpg config to pom.xml

- src/test/java/org/cactoos/io/TeeInputFromCharSequenceTest.java
- src/test/java/org/cactoos/io/TeeInputFromPathTest.java
#1372
- Correct TeeInput tests, if the path contains content
> 1372 Correct TeeInput tests

- src/test/java/org/cactoos/scalar/NumberOfTest.java
- src/test/java/org/cactoos/scalar/PropertiesOfTest.java
- src/test/java/org/cactoos/scalar/ReducedTest.java
- src/test/java/org/cactoos/scalar/ScalarWithFallbackTest.java
- src/test/java/org/cactoos/scalar/package-info.java
> #1375: Scalar - Replacing usage of MatcherAssert.assertThat

- src/test/java/org/cactoos/scalar/LengthOfTest.java
- src/test/java/org/cactoos/scalar/MultiplicationOfTest.java
- src/test/java/org/cactoos/scalar/NotTest.java
- src/test/java/org/cactoos/scalar/TrueTest.java
- src/test/java/org/cactoos/scalar/package-info.java
> For #1389: Scalar - Replacing usage of MatcherAssert.assertThat

- src/test/java/org/cactoos/io/TeeInputFromPathTest.java
- src/test/java/org/cactoos/io/TeeInputFromReaderTest.java
- src/test/java/org/cactoos/io/TeeInputFromTextTest.java
- src/test/java/org/cactoos/io/TeeInputFromUrlTest.java
> For #1381: TeeInput - Test the content of the file

- src/test/java/org/cactoos/io/TeeInputFromByteArrayTest.java
- src/test/java/org/cactoos/io/TeeInputFromFileTest.java
- src/test/java/org/cactoos/io/TeeInputFromInputTest.java
- src/test/java/org/cactoos/io/TeeInputFromReaderTest.java
>  Fix some more TeeInput tests

- src/main/java/org/cactoos/io/BytesOf.java
- src/main/java/org/cactoos/iterable/IterableOfBytes.java
- src/main/java/org/cactoos/iterable/IterableOfChars.java
- src/main/java/org/cactoos/iterator/IteratorOfBytes.java
- src/main/java/org/cactoos/iterator/IteratorOfChars.java
- src/main/java/org/cactoos/text/TextOf.java
- src/test/java/org/cactoos/io/BytesOfTest.java
- src/test/java/org/cactoos/iterable/IterableOfBytesTest.java
- src/test/java/org/cactoos/iterable/IterableOfCharsTest.java
- src/test/java/org/cactoos/iterator/IteratorOfBytesTest.java
- src/test/java/org/cactoos/iterator/IteratorOfCharsTest.java
- src/test/java/org/cactoos/text/TextOfTest.java
This is for #1397
Added
- `IterableOfChars(Text)`
- `IterableOfBytes(Text)`
- `IteratorOfChars(Text)`
- `IteratorOfBytes(Text)`
- `IteratorOfBytes(Bytes)`
- `BytesOf(Iterator<Bytes>)`
- `BytesOf(Iterable<Bytes>)`
- `TextOf(Iterator<Char>)`
- `TextOf(Iterable<Char>)`
> For #1397: Add more constructors 

- .rultor.yml
- README.md
For #1404:
- changed architect configuration in `rultor.yml`
- changed architect in `readme.md`
> For #1404: setting victornoel as architect

- src/test/java/org/cactoos/iterator/CycledTest.java
- src/test/java/org/cactoos/iterator/HeadOfTest.java
- src/test/java/org/cactoos/iterator/ImmutableTest.java
- src/test/java/org/cactoos/iterator/IteratorOfBooleansTest.java
- src/test/java/org/cactoos/iterator/IteratorOfBytesTest.java
- src/test/java/org/cactoos/iterator/IteratorOfCharsTest.java
- src/test/java/org/cactoos/iterator/IteratorOfDoublesTest.java
- src/test/java/org/cactoos/iterator/IteratorOfFloatsTest.java
- src/test/java/org/cactoos/iterator/IteratorOfIntsTest.java
- src/test/java/org/cactoos/iterator/IteratorOfLongsTest.java
- src/test/java/org/cactoos/iterator/IteratorOfShortsTest.java
- src/test/java/org/cactoos/iterator/IteratorOfTest.java
- src/test/java/org/cactoos/iterator/PartitionedTest.java
- src/test/java/org/cactoos/iterator/RepeatedTest.java
- src/test/java/org/cactoos/iterator/ShuffledTest.java
- src/test/java/org/cactoos/iterator/SortedTest.java
- src/test/java/org/cactoos/iterator/TailOfTest.java
- src/test/java/org/cactoos/package-info.java
#1420: 
- replace hamcrest MatcherAssert.assertThat with cactoos-matchers Assertion
> #1420 iterator package

- src/main/java/org/cactoos/text/HexOf.java
- src/main/java/org/cactoos/text/Randomized.java
- src/main/java/org/cactoos/text/Trimmed.java
- src/main/java/org/cactoos/text/TrimmedLeft.java
- src/main/java/org/cactoos/text/TrimmedRight.java
- src/main/java/org/cactoos/text/UncheckedText.java
- src/main/java/org/cactoos/text/Upper.java
- src/test/java/org/cactoos/io/AppendToTest.java
- src/test/java/org/cactoos/iterator/ImmutableTest.java
- src/test/java/org/cactoos/text/RandomizedTest.java
#1135 - replacing implements Text with extends TextEnvelope
- I've applied the new pattern for 6 classes and added a todo to continue the work.
> #1135: Extends TextEnvelope when possible

- src/main/java/org/cactoos/text/Sticky.java
- src/test/java/org/cactoos/text/StickyTest.java
- Add `Sticky` implementation for `Text`
- This is for #1423
> For #1423: Add Sticky decorator for Text

- src/main/java/org/cactoos/scalar/ScalarOf.java
- Just remove todo
- Actual work was done in https://github.com/yegor256/cactoos/pull/1435
> #1349: Remove todo

- src/test/java/org/cactoos/io/SlowInputStream.java
- src/test/java/org/cactoos/io/SlowInputStreamTest.java
Per #1132: 
- Add test
- Fix bug
> #1132: Fix bug in SlowInputStream

- src/main/java/org/cactoos/text/Concatenated.java
- src/test/java/org/cactoos/text/ConctatenatedTest.java
Hi
I would like to propose to add new class which allow concatenate texts.
Signed-off-by: kokodyn <kokodyn@gmail.com>
> Added Concatenated class to allow concatenate texts

- src/main/java/org/cactoos/list/ListIteratorNoNulls.java
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:
- You made a small amount of changes (less than 100 lines, less than 10 files)
- You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
- You are ready to defend your changes (there will be a code review)
- You don't touch what you don't understand
- You ran the build locally and it passed
- Title begins with the issue's number, then a short title
- Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
- Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).
- You ran …
> 1479 | fix previous typo

- src/main/java/org/cactoos/text/IsBlank.java
- src/main/java/org/cactoos/text/IsEmpty.java
- src/test/java/org/cactoos/text/IsEmptyTest.java
I would like to introduce a class in order to check whether the text is empty or not
Signed-off-by: kokodyn <kokodyn@gmail.com>
> Add IsEmpty to check if Text is empty or not

- .github/workflows/build.yml
- src/main/java/org/cactoos/iterator/TailOf.java
Per #1415
- Fix complilation on 11 ~~& 14~~
- Add 11 ~~& 14~~ to Github actions
> #1415: Run tests on Java 11

- src/main/java/org/cactoos/scalar/LengthOf.java
- src/test/java/org/cactoos/scalar/LengthOfTest.java
Per #1489 
- Add ctor for Text
> #1489: Make LengthOf accept Text in ctor

- src/main/java/org/cactoos/iterable/Matched.java
- src/main/java/org/cactoos/iterator/Matched.java
- src/test/java/org/cactoos/iterable/MatchedTest.java
- src/test/java/org/cactoos/iterator/MatchedTest.java
Per #1481 
- Add `iterator.Matched`
- Base `iterable.Matched` on it
> #1481: Introduce iterator.Matched

- src/main/java/org/cactoos/scalar/MaxOf.java
- src/main/java/org/cactoos/scalar/MinOf.java
- src/test/java/org/cactoos/scalar/MaxOfTest.java
- src/test/java/org/cactoos/scalar/MinOfTest.java
Per #1500 
- Delegate to primary constructor for Number
> #1500: Remove duplicated code from `MaxOf` & `MinOf`

- src/main/java/org/cactoos/text/Concatenated.java
- src/test/java/org/cactoos/text/ConctatenatedTest.java
Change related with #1051. I see i has been partly covered in PR #1480. Adding ctor which accepts String vargs in ctor is also required.
> #1051 add ctor with vargs String

- pom.xml
- src/main/java/org/cactoos/iterable/IterableOf.java
- src/main/java/org/cactoos/iterable/Joined.java
- src/main/java/org/cactoos/iterable/Sticky.java
- src/main/java/org/cactoos/iterator/Joined.java
- src/main/java/org/cactoos/map/MapOf.java
- src/main/java/org/cactoos/scalar/MultiplicationOf.java
- src/main/java/org/cactoos/scalar/PropertiesOf.java
- src/main/java/org/cactoos/scalar/SumOf.java
- src/main/java/org/cactoos/scalar/SumOfDouble.java
- src/main/java/org/cactoos/scalar/SumOfFloat.java
- src/main/java/org/cactoos/scalar/SumOfInt.java
- src/main/java/org/cactoos/scalar/SumOfLong.java
- src/main/java/org/cactoos/scalar/SumOfScalar.java
- src/test/java/org/cactoos/func/ChainedTest.java
- src/test/java/org/cactoos/iterable/JoinedTest.java
- src/test/java/org/cactoos/iterable/SolidTest.java
- src/test/java/org/cactoos/iterator/JoinedTest.java
- src/test/java/org/cactoos/list/ListOfTest.java
- src/test/java/org/cactoos/scalar/AndInThreadsTest.java
- src/test/java/org/cactoos/scalar/PropertiesOfTest.java
- src/test/java/org/cactoos/scalar/ReducedTest.java
- src/test/java/org/cactoos/scalar/SumOfScalarTest.java
- src/test/java/org/cactoos/set/SortedTest.java
This is for #1513.
It bumps cactoos-matchers to latest version and fix build.
I also took the liberty of fixing typing errors that would appear in my IDE but not during the build, as well as simplifying a bit of code while I was at it.
> 1513 fix build

- src/test/java/org/cactoos/collection/ImmutableTest.java
- src/test/java/org/cactoos/collection/NoNullsTest.java
Per #1470 
- Improve test based on problems found in #1470
> #1470: Improve test coverage for org.cactoos.collection

- src/main/java/org/cactoos/list/ListIteratorNoNulls.java
- src/test/java/org/cactoos/list/ListIteratorNoNullsTest.java
Per #1459 :
- Add no null check for `#add(`) and `#set()`
- Add tests to assure they're working properly
- Remove the puzzle
> #1459: ListIteratorNoNulls checks for #add() and #set()

- src/main/java/org/cactoos/iterable/Repeated.java
- src/main/java/org/cactoos/iterator/Repeated.java
- src/main/java/org/cactoos/scalar/AvgOf.java
- src/main/java/org/cactoos/text/FormattedText.java
- src/main/java/org/cactoos/text/Rotated.java
- src/main/java/org/cactoos/text/Split.java
A bunch of fixes related to previous issues, see commits for details.
> Missing fixes

- src/main/java/org/cactoos/iterator/Joined.java
- src/test/java/org/cactoos/iterator/JoinedTest.java
Add ctor and test
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:
- You made a small amount of changes (less than 100 lines, less than 10 files)
- You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
- You are ready to defend your changes (there will be a code review)
- You don't touch what you don't understand
- You ran the build locally and it passed
- Title begins with the issue's number, then a short title
- Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
- Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywor …
> #1508 Joined(items, item) ctor is missing

- src/main/java/org/cactoos/io/ResourceOf.java
- src/test/java/org/cactoos/io/ResourceOfTest.java
I added the ctor, as per #1517
> #1517 new ctor for ResourceOf

- src/main/java/org/cactoos/func/Flattened.java
- src/main/java/org/cactoos/func/FuncOf.java
- src/main/java/org/cactoos/scalar/Flattened.java
- src/main/java/org/cactoos/text/Abbreviated.java
- src/main/java/org/cactoos/text/Capitalized.java
- src/main/java/org/cactoos/text/Flattened.java
- src/main/java/org/cactoos/text/PaddedStart.java
- src/main/java/org/cactoos/text/Sub.java
- src/main/java/org/cactoos/text/SuffixOf.java
- src/test/java/org/cactoos/func/FlattenedTest.java
- src/test/java/org/cactoos/scalar/FlattenedTest.java
- src/test/java/org/cactoos/text/AbbreviatedTest.java
- src/test/java/org/cactoos/text/FlattenedTest.java
> (#1460) Introduce Flattened and use it where relevant

- src/main/java/org/cactoos/scalar/Xor.java
- src/test/java/org/cactoos/scalar/XorTest.java
Hi
I would like to propose to add new class which allow logical operation Xor.
> #1510 add Xor class to allow exclusive disjunction

- src/main/java/org/cactoos/iterator/RangeOf.java
- src/test/java/org/cactoos/iterator/RangeOfTest.java
#906
- Implements RangeOf for Iterator
- Implements test case for RangeOf
> (#906) Implements RangeOf for iterator

- src/main/java/org/cactoos/scalar/Equals.java
- src/main/java/org/cactoos/scalar/ScalarWithFallback.java
- src/test/java/org/cactoos/scalar/EqualsTest.java
> Improve scalar.Equals

- src/main/java/org/cactoos/BiFunc.java
- src/main/java/org/cactoos/BiProc.java
- src/main/java/org/cactoos/Bytes.java
- src/main/java/org/cactoos/Func.java
- src/main/java/org/cactoos/Input.java
- src/main/java/org/cactoos/Output.java
- src/main/java/org/cactoos/Proc.java
- src/main/java/org/cactoos/Scalar.java
- src/main/java/org/cactoos/Text.java
#1502
- Added the @FunctionalInterface annotation into all the cactoos interfaces that could be considered a functional interface.
> (#1502) Added @FunctionalInterface to all the cactoos functional interfaces

- src/main/java/org/cactoos/text/Newline.java
- src/test/java/org/cactoos/text/NewlineTest.java
#1498
- Implemented the Newline that returns a text that is the default system line separator
> (#1498) Added 'text.Newline'

- src/test/java/org/cactoos/iterable/CycledTest.java
- src/test/java/org/cactoos/iterable/EndlessTest.java
- src/test/java/org/cactoos/iterable/FilteredTest.java
- src/test/java/org/cactoos/iterable/HeadOfTest.java
- src/test/java/org/cactoos/iterable/IterableOfBooleansTest.java
- src/test/java/org/cactoos/iterable/IterableOfDoublesTest.java
- src/test/java/org/cactoos/iterable/IterableOfFloatsTest.java
- src/test/java/org/cactoos/iterable/IterableOfIntsTest.java
- src/test/java/org/cactoos/iterable/IterableOfLongsTest.java
- src/test/java/org/cactoos/iterable/IterableOfShortsTest.java
- src/test/java/org/cactoos/iterable/IterableOfTest.java
- src/test/java/org/cactoos/iterable/MappedTest.java
- src/test/java/org/cactoos/iterable/MatchedTest.java
- src/test/java/org/cactoos/iterable/PartitionedTest.java
- src/test/java/org/cactoos/iterable/RangeOfTest.java
- src/test/java/org/cactoos/package-info.java
For #1425
- Change MatchAssert
> (#1425) Replace MatcherAssert in a part of test package iterable

- src/main/java/org/cactoos/text/Sticky.java
- src/test/java/org/cactoos/text/StickyTest.java
For #1582:
- Base `text.Sticky` on `TextEnvelope`
> Add `toString`, `equals` & `hashCode` to `text.Sticky`

- src/main/java/org/cactoos/iterable/Matched.java
- src/main/java/org/cactoos/iterable/RangeOf.java
- src/test/java/org/cactoos/iterable/MatchedTest.java
- src/test/java/org/cactoos/iterable/RangeOfTest.java
Per #1592 
- Make `RangeOf` immutable
- Make `Matched` immutable
> Make `RangeOf` & `Matched` immutable

- pom.xml
- src/test/java/org/cactoos/bytes/HexOfTest.java
- src/test/java/org/cactoos/collection/BehavesAsCollection.java
- src/test/java/org/cactoos/experimental/ThreadsTest.java
- src/test/java/org/cactoos/func/AsyncTest.java
- src/test/java/org/cactoos/func/BiFuncOfTest.java
- src/test/java/org/cactoos/func/FuncOfTest.java
- src/test/java/org/cactoos/io/CloseShieldInputStreamTest.java
- src/test/java/org/cactoos/io/InputOfTest.java
- src/test/java/org/cactoos/io/InputStreamOfTest.java
- src/test/java/org/cactoos/io/StickyTest.java
- src/test/java/org/cactoos/io/TempFileTest.java
- src/test/java/org/cactoos/iterator/IteratorOfBytesTest.java
- src/test/java/org/cactoos/iterator/NoNullsTest.java
- src/test/java/org/cactoos/list/BehavesAsList.java
- src/test/java/org/cactoos/proc/BiProcOfTest.java
- src/test/java/org/cactoos/proc/ProcOfTest.java
- src/test/java/org/cactoos/proc/RunnableOfTest.java
- src/test/java/org/cactoos/scalar/ScalarOfTest.java
> (#1597) Bump cactoos-matchers to 0.25

- src/main/java/org/cactoos/iterable/Paged.java
- src/main/java/org/cactoos/iterator/Paged.java
- src/test/java/org/cactoos/iterable/PagedTest.java
- src/test/java/org/cactoos/iterator/PagedTest.java
The PR is related to #1538, but also has solution for #1537, because they are interconnected.
> (#1538) - replace the constructor to use an iterable

- src/main/java/org/cactoos/text/Concatenated.java
- Make `Concatenated` final as other classes
> Make `Concatenated` final

- src/main/java/org/cactoos/iterable/Shuffled.java
- src/main/java/org/cactoos/iterator/Shuffled.java
- src/test/java/org/cactoos/iterable/ShuffledTest.java
- src/test/java/org/cactoos/iterator/ShuffledTest.java
- Shuffle with a specific randomizer
> Make `Random` a parameter for `Shuffled`

- src/main/java/org/cactoos/proc/BiProcOf.java
- src/test/java/org/cactoos/proc/BiProcOfTest.java
- Add ctor for creating `BiProc` from two `Procs`
> Create `BiProc` from two `Proc`

- src/main/java/org/cactoos/func/FuncOf.java
- src/main/java/org/cactoos/proc/ForEach.java
- src/test/java/org/cactoos/proc/ForEachTest.java
> Use proper generics in `ForEach`

- src/main/java/org/cactoos/map/MapOf.java
- src/test/java/org/cactoos/map/MapOfTest.java
For issue #1618 
Added new constructors:
* `MapOf(map, X, Y)`
* `MapOf(X, Y)`
And tests
> (#1618) MapOf(map, X, Y) and MapOf(X, Y) new ctors

- src/main/java/org/cactoos/func/BiFuncEnvelope.java
- src/main/java/org/cactoos/func/BiFuncOf.java
- src/main/java/org/cactoos/func/SolidBiFunc.java
> Fix typo in name BiFuncEnvelope

- src/main/java/org/cactoos/text/StartsWith.java
- src/test/java/org/cactoos/text/StartsWithTest.java
Add all combinations for parameters
> Add more constructors for StartsWith class

- src/main/java/org/cactoos/io/InputWithRetry.java
- src/test/java/org/cactoos/io/InputWithRetryTest.java
Add InputWithRetry with retry logic on Input stream
@yegor256 Is this something you meant in this [Issue](https://github.com/yegor256/cactoos/issues/1735)
> Add InputWithRetry 

- .github/workflows/mvn.yml
https://github.com/yegor256/cactoos/issues/1752
> Update mac-os 12 to mac-os 15

- src/test/java/org/cactoos/map/NoNullsTest.java
Added tests that cover `put` and `remove` methods of `NoNulls` map class.
> Improve NoNulls map code coverage

- src/test/java/org/cactoos/list/NoNullsTest.java
Fully covered `indexOf`, `lastIndexOf`, `size` and `isEmpty` methods of `NoNulls` list class.
> Improve NoNulls list code coverage 

- src/test/java/org/cactoos/func/FlattenedTest.java
- src/test/java/org/cactoos/package-info.java
- src/test/java/org/cactoos/scalar/FlattenedTest.java
- src/test/java/org/cactoos/text/FlattenedTest.java
Fixed all warnings so that builds succeed.
> Fix build warnings

- src/test/java/org/cactoos/list/NoNullsTest.java
Added more tests for no nulls list. Covered these methods: `clear`, `contains`, `set`, `add`.
> More list tests

- src/test/java/org/cactoos/iterable/SortedTest.java
Added more tests for sorted iterable. Covered constructors that use varargs. `Sorted.java` is now fully covered.
> More sorted iterable tests

- src/test/java/org/cactoos/list/NoNullsTest.java
Wrote additional tests for `list\NoNulls.java`. Covered these methods: `addAll(items)`, `addAll(index, items)`, `removeAll(items)`.
> Add more no nulls list tests

- src/test/java/org/cactoos/iterable/CycledTest.java
- src/test/java/org/cactoos/iterable/FilteredTest.java
- src/test/java/org/cactoos/iterable/HeadOfTest.java
- src/test/java/org/cactoos/iterable/IterableOfBytesTest.java
- src/test/java/org/cactoos/iterable/ReversedTest.java
- src/test/java/org/cactoos/iterable/ShuffledTest.java
Wrote tests for iterable classes. Now `Cycled`, `Filtered`, `HeadOf`, `IterableOfBytes`, `Reversed` and `Shuffled` are fully covered.
> Add iterable tests

- pom.xml
> #1787: Update junit and qulice-maven-plugin
